### PR TITLE
Do not match the 'code' keyword when part of of longer word

### PR DESCRIPTION
**Pull request by ipkiss42**
Fixes #3114

### CODE REVIEW

**Comment by aiotter** [comment]
It looks a good approach. 
Just a reminder that you need to fix the doc as well.
https://github.com/dense-analysis/ale/blob/dc054f30c8356fecbe19e54aab60ff2587a6d71b/doc/ale.txt#L849-L879

**Comment by ipkiss42** [comment]
To be clear, this commit does not introduce `<code>` instead of `code` as keyword (it wouldn't be backwards-compatible). It still uses `code`, but uses the `\<` and `\>` zero-width patterns to enforce word boundaries. Note that the backslashes are not there due to the `\v` in the regular expression.

So I don't think that the doc needs to be changed, but let me know if I missed something.

**Comment by w0rp** [comment]
Thanks for the attempt! I went with #3114 in case someone wants to use some character around `code` that doesn't count as a boundary character. It should fix the issue.

**Comment by aiotter** [comment]
According to the current doc, they can set the formatting variable `%Code_code%` to make it shown as `Code_E001`. In your implementation they cannot.
But it's rare case. You may have no need to specify it on doc.

**Comment by aiotter** [comment]
Whoops I reloaded the browser to know w0rp has already closed the issue XD

**Pull request closed without merging**
