### PR TITLE
[lsp] Improve default root directory for Texlab

### PR DESCRIPTION
**Pull request by rliang**
Now defaults to the directory of the file.

### CODE REVIEW

**Comment by w0rp** [comment]
This default could cause problems. This would cause ALE to start a language server process for each directory you open.

**Comment by rliang** [comment]
I see. The more fundamental problem here seems to be that LaTeX does not have the concept of a "project".

Maybe use ".git" folders then?

**Comment by w0rp** [comment]
Yeah. You can also override any of the functions for determining the project root automatically with the `ale_lsp_root` setting.

**Comment by w0rp** [comment]
Closed due to inactivity.

**Pull request closed without merging**
