### PR TITLE
Add remark-lint for a markdown fixer

### LINKED ISSUE #1211: Support fixing code with remark
ALE comes with **prettier** configured as fixer for markdown files.

But **remark** can also fix markdown files.

Currently **remark** is only configured as linter.

*prettier* as fixer for markdown can do one thing that *remark* does not: wrapping long lines.

*remark* has more output options.

So, in my workflow, I need both: first prettier, then remark. So in my .vimrc I have:

```vim
let g:ale_fixers.markdown = ['prettier', 'remark']
```

In order for this to work, remark has to be configured as fixer.
I did so, tentatively, and in my setup it works. This is what I did:

Added these lines to `autoload/ale/fix/registry.vim`:

```
\   'remark': {
\       'function': 'ale#fixers#remark#Fix',
\       'suggested_filetypes': ['markdown'],
\       'description': 'Fix Markdown files with remark.',
\   },
```

and I added the file `autoload/ale/fixers/remark.vim` with the following content:

```
" Description: Fixing Markdown files with remark.

call ale#Set('remark_executable', 'remark')
call ale#Set('remark_use_global', 0)

function! ale#fixers#remark#GetExecutable(buffer) abort
      return ale#node#FindExecutable(a:buffer, 'remark', [
          \   'node_modules/remark-cli/cli.js',
          \   'node_modules/.bin/remark',
          \])
endfunction


function! ale#fixers#remark#Fix(buffer) abort
    let l:executable = ale#fixers#remark#GetExecutable(a:buffer)

    return {
    \   'command': ale#Escape(l:executable),
    \}
endfunction
```

### PR DESCRIPTION
**Pull request by blyoa**
Closes #1211

This PR added [remark-lint](https://github.com/remarkjs/remark-lint#using-remark-to-fix-your-markdown) for a markdown fixer.

This feature is already reported in https://github.com/dense-analysis/ale/issues/1211, and this PR was based on code proposed by @dirkroorda there.

### CODE REVIEW

**Comment by blyoa** [comment]
Thank you for the review, and I'm sorry for the delay.
This PR does not introduce any new option and uses the same options of remark-lint for a linter. I referenced options of eslint, which works as both a linter and a fixer, and I did not add any description, but should I add it?

**Comment by dbellavista** [comment]
Hi @w0rp ! I was waiting for this merge request to be completed, I took a look at `:help ale-dev` but I think everything is in order. The documentation is missing because the tool is already documented and listed as supported, so I can't really find a place where to document this.

If @blyoa is not available to make the required changes I could replicate and fix the merge request

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by w0rp** [comment]
Nevermind the stale bot. I'm actually using it to get pull requests merged faster by automating it poking people for responses and getting some answers back.

**Pull request merged**
