### PR TITLE
Add biome (ex. rome) support for javascript

### PR DESCRIPTION
**Pull request by akiomik**
This PR adds biome as fixers.

* https://biomejs.dev

ref: #4674 #3280

### CODE REVIEW

**Review by hsanson — DISMISSED** [review]
Looks good, but tests are not passing.   Make sure supported-tools.md and doc/ale-supported-languages-and-tools.txt have listed the new tool in same order.

**Comment by akiomik** [comment]
Thank you for review, I've fixed it.

**Comment by akiomik** [comment]
I was mistaking Java for Javascript 😂
I've resolved conflicts.

**Review by hsanson — APPROVED** [review]
Thanks for the contribution and quick response.

**Pull request merged**
