### PR TITLE
Add F# language server

### PR DESCRIPTION
**Pull request by tani**
I added a language server for F#.
There are two problems.
- ALE will set a project root with `.git` directory, but I prefer to set a project root with `<project name>.fsproj`. I did not get how to get a project root with that file, because `ale#path#FindNearestFile` does not use wildcard matching. 
Please tell me if you know that.
- Since  F# language server is often installed in various directories, I keep the F# language server path empty. Thus, users should set the path `g:ale_fsharp_language_server_assembly` first.

P.S.
This request is work in progress.

### CODE REVIEW

**Comment by fgborges** [comment]
This pull request is blocked by https://github.com/fsprojects/fsharp-language-server/pull/70

**Comment by WinformsWizard** [comment]
The pull request got merged, so many this can be merged if it is updated?

**Comment by secana** [comment]
Any option to reopen this PR? F# support in ALE would be great.

**Comment by tani** [comment]
@secana Thank you for proposing it. I again check this pull request in my local environment.

**Comment by tani** [comment]
Creating a new request for FSAC is better than reopening this pull request because FSAC supports .NET 5 https://github.com/fsprojects/fsharp-language-server/issues/90. How about you ?

**Pull request closed without merging**
