### PR TITLE
Enable asyncronous linting for pylint

### PR DESCRIPTION
**Pull request by oliverwiegers**
When [pylint.vim](https://github.com/dense-analysis/ale/blob/master/ale_linters/python/pylint.vim) was written pylint wasn't able to read from stdin. As mentioned in [issue 590](https://github.com/dense-analysis/ale/issues/590) this causes the A.L.E. linting using pylint to not be async. 

Since [Pull request 2746](https://github.com/PyCQA/pylint/pull/2746) is merged, pylint is able to read from stdin.

I added the pylint flag `--from-stdin` to the pylint call and changed [ale_linters/python/pylint.vim](https://github.com/oliverwiegers/ale/blob/43b78ad757cb112c20043468882a81c7b23f6b5d/ale_linters/python/pylint.vim) so that ale is continuously linting python files using pylint.

I haven't written additional tests, because the existing tests do cover my changes.  
I have edited [test/command_callback/test_pylint_command_callback.vader](https://github.com/oliverwiegers/ale/blob/43b78ad757cb112c20043468882a81c7b23f6b5d/test/command_callback/test_pylint_command_callback.vader) to call pylint the right way from pipenv.

### CODE REVIEW

**Comment by oliverwiegers** [comment]
Hello the bot marked this PR as stale. The test ran successfully, but the Travis CI is stuck.

**Comment by lithammer** [comment]
> If your pull request is good to merge, bother w0rp or another maintainer again, and get them to merge it.

Ping @w0rp (sorry, don't know who the other maintainers are)

**Comment by w0rp** [comment]
This will work with `pylint` 2.5.0, but will break with earlier versions. Not everyone will have updated, so we should check the version for a while.

Another issue is that you can't mark a linter as optionally being one that only lints when you save a file or on any text edit. I've thought about making it so you can dynamically compute if a file can be checked or not, and I think I know how to make that possible now. I'll open an issue for that, do that first, and update this to use a version check.

**Comment by w0rp** [comment]
I've opened #3285 to support this. I want to get that one done now. It will open up a lot of new possibilities.

**Comment by oliverwiegers** [comment]
Okay, is there currently any todo for me?

**Comment by w0rp** [comment]
No, I'll take care of it. You need some support from me to get this done. The stale bot should be configured to let things stay open if someone leaves a comment, so this PR should remain open now.

**Comment by w0rp** [comment]
I've merged parts of this in the command line now. I had to fix how `lint_file` works, but I've tested it with different pylint, and it works with both the old and new versions.

Cheers! :beers:

**Pull request closed without merging**
