### PR TITLE
Add lexical for linting elixir projects

### PR DESCRIPTION
**Pull request by axelclark**
Add linter support for Elixir using [Lexical](https://github.com/lexical-lsp/lexical).  I followed the existing elixir linters as a template.  Let me know if I need to make changes.

### CODE REVIEW

**Comment by vais** [comment]
Just gotta say this - came here hoping to see that there's a PR to add lexical to ale and there is! Thank you for taking this up @axelclark ❤️

**Review by w0rp — CHANGES_REQUESTED** [review]
I fixed aligning doc tags. The custom checks for documentation and complaining about sorting sections of documentation and lists of supported tools alphabetically, so check that out.

**Comment by axelclark** [comment]
@w0rp thanks for fixing the alignment!  I pushed a change to fix the other test failure. Let me know if you have any other changes for me to make.

**Review by w0rp — APPROVED** [review]
Cheers! :beers:

**Pull request merged**
