### PR TITLE
fix #4276: honor b:ale_enabled for hover at cursor

### LINKED ISSUE #4276: [Got Error Message In Cmdline Window] Will have ale related error message when open cmdline window
## Information

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Operating System: macOS 12.5
## What went wrong

Errors in command line window.

## Reproducing the bug

1. `nvim ~/.vimrc`
2. Press `q:` , following errors occured:
image

### :ALEInfo

```
 Current Filetype: vim
Available Linters: ['ale_custom_linting_rules', 'vimls', 'vint']
  Enabled Linters: ['ale_custom_linting_rules', 'vimls', 'vint']
  Ignored Linters: []
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_vim_vimls_config = {}
let g:ale_vim_vimls_executable = 'vim-language-server'
let g:ale_vim_vimls_use_global = 0
let g:ale_vim_vint_executable = 'vint'
let g:ale_vim_vint_show_style_issues = 1
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let b:ale_enabled = 0
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gobuild', 'golangci-lint', 'gofmt', 'golint', 'staticcheck'], 'java': ['checkstyle', 'ccnlint'], 'cpp': ['cppcheck', 'cpplint', 'g++', 'clangtidy', 'cpplintx'], 'rust': ['analyzer', 'rls']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {'\.min.js$': {'ale_enabled': 0}, '/Users/hbliu/fabfile/.*': {'ale_enabled': 0}, '/Users/hbliu/.dotfiles/link/fabfile/.*': {'ale_enabled': 0}}
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 1
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

```

### PR DESCRIPTION
**Pull request by hiberabyss**

### CODE REVIEW

**Comment by hiberabyss** [comment]
Could anyone have a look of this?

**Comment by hsanson** [comment]
Lint tests are failing. Recommend enabling the ale custom linter for vim files so ALE let's you know about the issues:

```vimscript
let g:ale_linters = {
  \   'vim': ['ale_custom_linting_rules']
\}
```

**Comment by hiberabyss** [comment]
> Lint tests are failing. Recommend enabling the ale custom linter for vim files so ALE let's you know about the issues:
> 
> ```
> let g:ale_linters = {
>   \   'vim': ['ale_custom_linting_rules']
> \}
> ```

Update indention to avoid test failure.

**Review by hsanson — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
