### PR TITLE
Add CodeAction codeActionLiteralSupport Feature

### PR DESCRIPTION
**Pull request by sak96**
## Why the Pull Request?

As per [ale dev philosophy](https://github.com/dense-analysis/ale/wiki/ALE-Development-Philosophy#important-principles-for-ale-code) point 8 this feature is added to allow use code actions like import fixes, implementation of interfaces. This could fix `no code action received from server` mentioned in #3523.

The working is based on allowing lsp with capability `CodeActionClientCapabilities` with `codeActionLiteralSupport` to advertise as such.

## Tasks
- [x] get feature working
- [x] fix coding standards issue
- [x] write test cases for code
- [x] Add documentation

## References
- [LSP codeActionClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionClientCapabilities)

Credits: @Benabik for initial version

### CODE REVIEW

**Comment by Benabik** [comment]
Not sure how to raise visibility on this, but this does fix rust-analyzer *and* doesn't break tests, which is great.  Thanks for the improvements on my hasty code.

Even though I don't write a ton of Rust, this makes ALE far more useful.  The "Implement missing members" action alone is a huge productivity gain.

**Comment by sak96** [comment]
Yeah `Implement missing members` is really a quality of life improvement.

I wanted to debug it but i saw that you had already figure it out so i just improved your pr.

**Comment by sak96** [comment]
trying to insert some gentle reminder.
hope not offensive or irritating

@w0rp @hsanson 
 
 
image

**Comment by sak96** [comment]
```vim
max([value, 1])
```
Without the above `empty line has no code fixes`
codefix_max_column


With the above `empty line also has code fixes`
codefix

**Pull request merged**
