### PR TITLE
Add support for `rustywind` fixer

### PR DESCRIPTION
**Pull request by groig**
This PR adds support for [rustywind](https://github.com/avencera/rustywind), an utility to sort Tailwind CSS classes in html files.

### CODE REVIEW

**Review by hsanson — APPROVED** [review]
Thanks. Looks good.

**Comment by hsanson** [comment]
@groig Please fix the linter issues.

**Comment by groig** [comment]
> @groig Please fix the linter issues.

Done

**Comment by hsanson** [comment]
Seems the entry for rustywind is missing in the supported-tools.md file.

**Review by hsanson — APPROVED** [review]
Thanks. Looks good.

**Pull request merged**
