### PR TITLE
Add clangcheck linter for C

### PR DESCRIPTION
**Pull request by nganhkhoa**
This issue is stalled even though it is simple #976.

Document is to be added later on.

### CODE REVIEW

**Comment by w0rp** [comment]
Looks good. You just need to document the options, list it as an available linter for C, and add some tests.

**Comment by ariel-miculas** [comment]
any plans on this one?

**Comment by hsanson** [comment]
The source repo has been deleted so this PR is no longer mergeable.  The implementation looks ok so if interested submit a new PR with the same implementation, add documentation, tests, and updated list of supported tools.

**Comment by nganhkhoa** [comment]
I'm sorry but I don't use ALE anymore, so I am no longer need this. The PR is mostly a copy from the C++ version available.

**Pull request closed without merging**
