### PR TITLE
Fix FuzzyJSON when is already a JSON

### PR DESCRIPTION
**Pull request by Mte90**
A json is a dict so json_decode generate an error because expects a list.

Fix https://github.com/dense-analysis/ale/issues/3886

### CODE REVIEW

**Review by hsanson — CHANGES_REQUESTED** [review]
Thanks for the contribution but I think this is not good way to fix the problem.

The FuzzyJSONDecode() method is clear on what it expects as input (e.g. string or list of strings) so if the caller is sending something different than what is expected then the caller needs to be fixed.

Instead of modifying the FuzzyJSONDecode() method better modify the ale#completion#HandleUserData() method to check the user data and if a dictionary skip the json decoding step.

**Comment by Mte90** [comment]
Done :-)

**Comment by hsanson** [comment]
Seems to still have issues (tests failing).  I am closing this MR in favor of this other one #3894 that addresses the issue and further improves the conditional checks.

**Comment by Mte90** [comment]
Cool the important that a fix landed, I have not so much experience with VimL

**Pull request closed without merging**
