### PR TITLE
Add typescript-language-server support

### PR DESCRIPTION
**Pull request by soywod**
Added support of https://github.com/theia-ide/typescript-language-server, for both javascript and typescript. I'm using it since a while and I thought it could be useful to add them here :)

### CODE REVIEW

**Comment by soywod** [comment]
> Looks fine to me. Add some tests for the linters. See `:help ale-tests`. Should we try to find `tsconfig.json` first, instead of `package.json`?

It's pointless, because you can't have both javascript and tsconfig. I mean, if you have a tsconfig, you should use typescript instead of javascript.

**Comment by w0rp** [comment]
You could look for `jsconfig.json`.

**Comment by soywod** [comment]
It's not that common in web development, but yes it could be checked before `package.json`. I will update soon.

**Comment by omeid** [comment]
So what is blocking this?

**Comment by w0rp** [comment]
The thing blocking this was the lack of tests. If someone wants to open a new PR with tests, please do. If the author comes back, we can reopen the PR.

**Pull request closed without merging**
