### PR TITLE
dafny: add a timeLimit option and message-parsing

### PR DESCRIPTION
**Pull request by benknoble**
The option itself was manually tested.

The message-parsing has a new test.

#3390 should probably merge first, which will necessitate some updates to this PR.

### CODE REVIEW

**Comment by benknoble** [comment]
@w0rp should be passing

**Review by hsanson — APPROVED** [review]
Looks good. Tests in order too and no visible backward compatibility issues.

**Comment by benknoble** [comment]
@hsanson should we update `bufnr` to `filename` now that #3390 is merged, too? I'm actually surprised the tests passed after that

**Comment by hsanson** [comment]
@benknoble I do not use Dafny but from what I have read it seems using filenames would be useful in this case.  It will allow ALE to show errors  on files still not open (no buffer) in vim/nvim.

**Pull request merged**
