### PR TITLE
Allow erlfmt as fixer

### PR DESCRIPTION
**Pull request by gilacost**
I am learning erlang and I was suffering with the code no being formatted. After some research, I found the WhatsApp's [erlfmt](https://github.com/WhatsApp/erlfmt). I hope this is useful for someone. In order to use this you need erlfmt in your `rebar.config`.

### CODE REVIEW

**Comment by gilacost** [comment]
@w0rp could you review this, please? Is there anything missing?

**Comment by w0rp** [comment]
This is pretty good. Just rename everything to use `erl_fmt` or `erlfmt` everywhere consistently, across all of the file names, options, etc.

**Comment by gilacost** [comment]
> This is pretty good. Just rename everything to use `erl_fmt` or `erlfmt` everywhere consistently, across all of the file names, options, etc.

Renamed to erlfmt 😄 @w0rp 🚀

**Comment by gilacost** [comment]
@w0rp sorry to bother you but this has gone stale again, everything has been renamed to erlfmt 🙂

**Comment by gilacost** [comment]
@w0rp could you re-open and merge this? it is the second time that gets closed for being stale 😛 .

**Pull request closed without merging**
