### PR TITLE
Add CMake linter cmake-lint

### LINKED ISSUE #3396: cmake-format also provides cmake-lint
cmake-format support was merged in #2244 as a fixer. ALE also has support for [cmake-lint](https://github.com/richq/cmake-lint) which is currently unmaintained. However, cmake-format also defines cmake-lint:

> The cmake-format project provides Quality Assurance (QA) tools for cmake:
> 
> cmake-annotate can generate pretty HTML from your listfiles
> cmake-format can format your listfiles nicely so that they don't look like crap.
> cmake-lint can check your listfiles for problems
>ctest-to can parse a ctest output tree and translate it into a more structured format (either JSON or XML).

It can be added as a linter, which would currently be the only maintained CMake linter.

### PR DESCRIPTION
**Pull request by carlsmedstad**
Add support for the CMake linter cmake-lint provided by https://github.com/cheshirekow/cmake_format.

A bit unsure about the naming due to the conflict with the other linter for CMake.

Resolves #3396.

### CODE REVIEW

**Comment by offa** [comment]
Since the current linter is unmaintained, wouldn't it make sense to replace it with the new one?

**Comment by carlsmedstad** [comment]
The old linter has been forked and now lives in [cmake-lint/cmake-lint](https://github.com/cmake-lint/cmake-lint). Development is far from active, but I asked if the project was still maintained and the answer was [yes](https://github.com/cmake-lint/cmake-lint/issues/8#issuecomment-1008008173).

So I don't think it's fair to replace it really.

**Comment by offa** [comment]
Ah, thank you. I only knew the original repo.

**Review by hsanson — CHANGES_REQUESTED** [review]
Thanks, looks good. Just missing tests for the linter itself. Can you add one similar to `test/linter/test_ruby.vader`?  It tests if the correct default command is returned and if the options are properly set if configured.

**Comment by carlsmedstad** [comment]
Added the test and also wrapped the executable in `ale#Escape()` as I noticed that was the case for most other linters.

**Review by hsanson — APPROVED** [review]
Thanks for the contribution.

**Comment by hsanson** [comment]
@carlsmedstad @offa does this new linter replaces the current one available in ALE:

  - https://github.com/richq/cmake-lint

Wondering if we should consider removing it. I see from  that repo that there has not been any activity in the last 5 years. But that alone is not indiciation that the linter is not being used.

**Comment by carlsmedstad** [comment]
See my comment above for my opinion about that:

> The old linter has been forked and now lives in [cmake-lint/cmake-lint](https://github.com/cmake-lint/cmake-lint). Development is far from active, but I asked if the project was still maintained and the answer was https://github.com/cmake-lint/cmake-lint/issues/8#issuecomment-1008008173.
>
> So I don't think it's fair to replace it really.

I think we should update the URL to point to the new repository at least (https://github.com/cmake-lint/cmake-lint).

**Pull request merged**
