### PR TITLE
Add nvim floating window support

### PR DESCRIPTION
**Pull request by jargonzombies**
I'm in need of some guidance. From some floating window handling code from [gitgutter](https://github.com/airblade/vim-gitgutter), I've been able to cobble together neovim floating window support.

I've done the following:
- Added a `g:ale_float_preview` variable that enables/disables forwarding calls to `ale#preview#Show` to a function opening a floating window
- Tried to get to feature parity with everything going on in `ale#preview#Show` within the new function `ale#preview#ShowFloating` (commands, filetype, `stay_here`, etc.)

In combination with `g:ale_hover_to_preview`, this generates floats for LSP hover and lints (with `:ALEDetail`), and probably in a lot of other situations too.

Sticking points:
- Is this a good approach? Should it be an alternative to balloons instead?
- Does it make sense to implement `stay_here` functionality for a floating window? Should we bug out onto a regular preview if `stay_here` is false?
- How to test?
- In #2418, a requested feature is floating windows for "documentation while navigating the items in popup menu", but I have no idea what is meant. If they mean that they want hover for symbols in the completion popup, how could I go about adding that?

This is my first time messing around in vimscript, so please explain things as if I were a five year old, but also reasonably competent with google and `:help`.

### CODE REVIEW

**Comment by lithammer** [comment]
This is related to https://github.com/dense-analysis/ale/pull/2925.

**Comment by kevinclark** [comment]
@w0rp I'm interested in this too and would consider working through a patch, but I saw this close without a response. Is this something that would be accepted?

**Comment by w0rp** [comment]
I've reopened this. It really just need some kind of test for it.

**Comment by kevinclark** [comment]
Oh, great! @jargonzombies do you want to write the test and push it over the line, or should I pick it up?

**Comment by w0rp** [comment]
I think I might prefer to see this put in its own file and called from other files. `ale#preview#Show` is used for:

* Hover information
* `:ALEDetail`
* Errors if you configure them the right way
* Finding references
* Symbol search
* Handling an LSP "show message" response

Finding references and symbol search should always use the preview window so the `ftplugin` file can be loaded for making a selection. (`ftplugin/ale-preview-selection.vim`) The floating windows might be good for the rest, though I'm not sure about the "show message" response. It would be nice to be able to configure everything in one go, and also individually.

**Comment by jargonzombies** [comment]
@kevinclark Unfortunately, I'm really busy all the way until mid-January, so if you're willing to push this over the line, I would appreciate that.

**Comment by kevinclark** [comment]
@jargonzombies I'll give it a shot!

**Pull request closed without merging**
