### PR TITLE
codefix: Fix LSP MenuCallback invocation (E119, not enough args)

### PR DESCRIPTION
**Pull request by liskin**
> Where are the tests? Have you added tests? Have you updated the tests? Read the
> comment above and the documentation referenced in it first. Write tests!
> Seriously, read `:help ale-dev` and write tests.

Can the right-click menu be tested somehow? Dunno. :-(

### CODE REVIEW

**Comment by tmc** [comment]
Looking forward to this merging!

**Comment by liskin** [comment]
@w0rp @hsanson Any hints how to add a test for this?

**Comment by hsanson** [comment]
@liskin I have never encounter this error. Can you provide me instructions on how to trigger it so I can test the fix?

**Comment by liskin** [comment]
@hsanson

1. setup up right click to open popup (probably default in gvim, needs `set nocompatible mouse=a mousemodel=popup_setpos` in console vim)
2. open file where some LSP is active (I tested with python and `pyls`)
3. right click
4. boom, there's a E119 error

**Review by hsanson — APPROVED** [review]
Indeed this PR fixes a bug in the call.

**Pull request merged**
