### PR TITLE
Fix windows github action

### PR DESCRIPTION
**Pull request by sak96**
Fix github action for windows

Follow up for: #3554

update vader.vim:  junegunn/vader.vim#30

### CODE REVIEW

**Comment by sak96** [comment]
@hsanson @w0rp 

i would need some help for fixing failing test cases.
do let me know where to look for. it is mostly tsserver

**Comment by hsanson** [comment]
@sak96 thanks for the effort but we already tried to get this to work and failed. I do not have a single windows machine I can use to debug this so not sure I can help.

**Comment by sak96** [comment]
quick question: https://github.com/dense-analysis/ale/blob/34892186e44b21356c84e1c2e019f96a304c3edc/.appveyor.yml#L48

why is `test/*/*/*.vader test/*/*/*.vader` twice ?

**Comment by sak96** [comment]
ok i give up don't think it is easy without win machine.

**Comment by w0rp** [comment]
I appreciate the effort. We will get it to work... some day. I just don't think it's a priority for me.

**Pull request closed without merging**
