### PR TITLE
Elixir Credo: Support Umbrella Mix Projects

### PR DESCRIPTION
**Pull request by connorlay**
Hello! This is my first time contributing to this project, so please let me know if I missed anything in the contributing guide and `:help ale-dev` 😄 

This PR improves the experience of using the [credo](https://github.com/rrrene/credo) linter for Elixir by adding support for [umbrella mix projects](https://elixir-lang.org/getting-started/mix-otp/dependencies-and-umbrella-projects.html#umbrella-projects). For example, I have a project that defines a custom `.credo.exs` file at the root of the umbrella, rather than in each child application. I expect ALE to search for an umbrella root, as it does for the `elixir_ls` language server linter and fixer. What happens on `master` today is it executes `mix credo` in the child application, rather than the umbrella root, so the configuration file is not picked up.

I based this PR on the existing `elixir_ls` [implementation](https://github.com/dense-analysis/ale/blob/master/ale_linters/elixir/elixir_ls.vim#L19) and [tests](https://github.com/dense-analysis/ale/blob/master/test/command_callback/test_elixir_ls_command_callbacks.vader#L24) for determining the root of a mix project.

### CODE REVIEW

**Comment by RyanSquared** [comment]
This should work for both projects with and without Umbrella. Can you make a test both using and not using Umbrella filenames? This probably means just copying the "old" linter (before commit 988951b) and using the changes you applied in 988951b.

**Comment by connorlay** [comment]
@RyanSquared Thank you for the feedback. I added the tests you requested. I am new to using Vader so if you have ideas for how I can reduce repetition in this file I am all ears!

**Comment by connorlay** [comment]
@RyanSquared This PR has been open for a while. Is there anything else you would like to see changed, or is this ready to be merged in? Thanks!

**Comment by cblavier** [comment]
need this feature too!
thanks for opening the PR @connorlay

**Comment by connorlay** [comment]
@w0rp Would it be possible to get this PR merged? This is a nice quality of life improvement for Elixir development. Thanks!

**Comment by puyo** [comment]
+1, I need this. I had to monkey patch this function in my .vimrc

**Comment by connorlay** [comment]
@w0rp Hello! I was pinged by the stale bot on this PR. Is there anything else you would like to see on this, or can it be merged? Thanks!

**Pull request closed without merging**
