### PR TITLE
Update elm-ls

### PR DESCRIPTION
**Pull request by andys8**
* elm_lsp is now elm_ls
* The binary published by @elm-tooling is elm-language-server

Updates tests, docs and adds more options to the plugin.

Solved #2592

### CODE REVIEW

**Comment by andys8** [comment]
@w0rp Did you have to time to look into the changes? It's mostly updating the changes made to the configuration in `elm-language-server`. The current `master` will not work.

**Comment by antew** [comment]
Thank you for putting this together @andys8!

The only thing I think we may need to add is a fallback to looking for `elm-lsp` if `elm-language-server` executable is not found, that way for people who have the `elm-lsp` npm package installed will  be able to use their existing config if they upgrade ALE.

**Comment by andys8** [comment]
@antew Yeah, right, makes sense.

Is https://github.com/w0rp/ale/commit/9317184dd32d1c40fca0048ec6ec6c38dd6dfb81 looking fine for you?

**Comment by antew** [comment]
Looks good to me!

**Comment by RyanSquared** [comment]
The only issue I have with this is that options for the previous linter are not carried over to the new one. I'm not sure what the policy is on that kind of thing.

**Comment by andys8** [comment]
@RyanSquared Regarding backwards compatibility of options?

The previous linter was before there was a release of the language server, and is currently incompatible.

**Comment by andys8** [comment]
Is there anything else I can do to get this merged? :)

**Comment by kornicameister** [comment]
Trying out it via: https://github.com/kornicameister/dotfiles/pull/710

For now I can tell that something nice is happening :). That's the screenshot of my Elm project:
image

**Pull request merged**
