### PR TITLE
Added ocamllsp

### PR DESCRIPTION
**Pull request by Risto-Stevcev**
This adds the new official [OCaml language server](https://github.com/ocaml/ocaml-lsp) ([ols](https://github.com/ocaml-lsp/ocaml-language-server) is archived)

### CODE REVIEW

**Comment by Risto-Stevcev** [comment]
The linters test fails but I'm not sure what's going on and what needs to be done there:
```
========================================                                                                                                                                      
Checking for invalid tag references                                                    
========================================                                                                                                                                      
Invalid tag references tags follow:                                                    
                                                                                       
========================================                                               
diff supported-tools.md and doc/ale-supported-languages-and-tools.txt tables           
========================================                                               
Differences follow:                                                                                                                                                           
                                                                                                                                                                              
--- /tmp/doc-sorted.XXFaDlBG                                                           
+++ /tmp/doc.XXFolFPC                                                                  
@@ -245 +244,0 @@                                                                      
-OCaml - ocamllsp                                                                      
@@ -246,0 +246 @@                                                                      
+OCaml - ocamllsp                                                                      
                                                                                       
The supported tools list isn't sorted properly           
```

**Comment by hsanson** [comment]
@Risto-Stevcev make sure that "ocamllsp" is listed before "ocp-indent" everywhere they are listed so they are sorted in alphabetical order:

```
   * [merlin](https://github.com/the-lambda-church/merlin)
   * [ocamlformat](https://github.com/ocaml-ppx/ocamlformat)
   * [ocamllsp](https://github.com/ocaml/ocaml-lsp)      
   * [ocp-indent](https://github.com/OCamlPro/ocp-indent)                                                                                                      
 ￼ * [ols](https://github.com/freebroccolo/ocaml-language-server)
```

This order must be the same on these files:

  - ale.txt
  - ale-supported-languages-and-tools.txt
  - supported-tools.md

Not 100% sure about this one but for consistency also ale-ocaml.txt.

If you have docker daemon running on your machine you can run the linter-only tests locally to check if everything is ok before pushing your changes to Github:

```sh
./run-tests --linters-only
```

**Comment by Risto-Stevcev** [comment]
Ah thanks, all the checks are passing now

**Review by hsanson — APPROVED** [review]
Thanks for the addition.

**Pull request merged**
