### PR TITLE
Fix clang-tidy ignoring compile-commands.json

### PR DESCRIPTION
**Pull request by fenuks**
Simple fix for #3506.

### CODE REVIEW

**Comment by hsanson** [comment]
ALE migrated from Travis to Github Actions (see #3548) so it is necessary to rebase this PR from latest master branch to trigger the required checks.

```
# Add dense-analysis as remote upstream on your local fork. Not 
# needed if already added.
git remote add upstream https://github.com/dense-analysis/ale.git

# Sync your local master with upstream master
git checkout master
git fetch upstream master
git merge upstream/master

# Rebase the PR branch with master
git checkout my-branch-name
git rebase master   # Fix any conflicts you may have

# Force push the updated PR branch to origin to trigger the checks
git push -f origin my-branch-name
```

**Review by hsanson — APPROVED** [review]
Seems correct.  Cannot test so trusting the author it is working.

**Comment by fenuks** [comment]
To my best knowledge, it is. ;) Also found information [here](https://clang.llvm.org/docs/ClangCheck.html) (at the very bottom) that
> The ‘–’ at the end is important as it prevents clang-check from searching for a compilation database.

Apparently it applies to clang-tidy as well.

**Comment by laino** [comment]
This fixed the issue for me. Great work and thank you!

**Pull request merged**
