### PR TITLE
Add Stoplight Spectral linter for yaml

### PR DESCRIPTION
**Pull request by t2h5**
- Add Stoplight Spectral linter for yaml and json.
  - https://github.com/stoplightio/spectral
  - It helps to edit OpenAPI Schema.

image

### CODE REVIEW

**Review by hsanson — COMMENTED** [review]
This linter is very useful, did not know about it.  Would be great if this PR also added support for JSON files. It should not be difficult to achieve.

**Comment by t2h5** [comment]
Added JSON support.

**Comment by hsanson** [comment]
@w0rp seems travis CI is somehow stuck... may PRs are waiting for status report and cannot be merged.

**Review by hsanson — DISMISSED** [review]
Changes are good and tested the linter works properly on my own openapi yaml and json definitions.

**Comment by hsanson** [comment]
ALE migrated from Travis to Github Actions (see #3548) so it is necessary to rebase this PR from latest master branch to trigger the required checks.

```
# Add dense-analysis as remote upstream on your local fork. Not 
# needed if already added.
git remote add upstream https://github.com/dense-analysis/ale.git

# Sync your local master with upstream master
git checkout master
git fetch upstream master
git merge upstream/master

# Rebase the PR branch with master
git checkout my-branch-name
git rebase master   # Fix any conflicts you may have

# Force push the updated PR branch to origin to trigger the checks
git push -f origin my-branch-name
```

**Review by hsanson — APPROVED** [review]
Good to go, thanks.

**Pull request merged**
