### PR TITLE
Allows to use quickfix for references.

### LINKED ISSUE #1759: quickfix list support for ALEFindReferences and commands for navigating through references
If I've got a list of references then there's a decent chance that I'll want to cycle through them.

Suggest using the quickfix list on the grounds that: that's what `cscope` and `YouCompleteMe` both do in analogous situations, so it's probably what people are used to.

### PR DESCRIPTION
**Pull request by daliusd**
E.g. following mapping could be used to find references for item under
cursor and put result into quickfix list:

```
nnoremap <leader>af :ALEFindReferences -quickfix<CR>
```

Fixes #1759

### CODE REVIEW

**Comment by daliusd** [comment]
@hsanson please review.

**Review by hsanson — CHANGES_REQUESTED** [review]
Works fine with my limited testing usin Solargraph LSP. Thanks.

I just would like to have the documention also updated to include the new option `:h ALEFindReferences`. Also mention that the -relative option has no effect if -quickfix is used.

Finally not sure but maybe would be good to automatically open the quickfix if it is not open?

**Comment by daliusd** [comment]
> Works fine with my limited testing usin Solargraph LSP. Thanks.

Cool. I have tested with `tsserver` and `pyright`.
 
> I just would like to have the documention also updated to include the new option `:h ALEFindReferences`. Also mention that the -relative option has no effect if -quickfix is used.

Documentation updated.

> Finally not sure but maybe would be good to automatically open the quickfix if it is not open?

Vim `grep` command does not open quickfix list by default. I personally never open quickfix list. Here is suggestion how to open quickfix list window for `grep` command that must work for `ALEFindReferences` if there is a need: https://www.reddit.com/r/vim/comments/bmh977/comment/emwjm7h/?utm_source=share&utm_medium=web2x&context=3

**Review by hsanson — APPROVED** [review]
Great, thanks for the changes.

**Comment by daliusd** [comment]
🍻

**Pull request merged**
