### PR TITLE
Use maven wrapper if available

### PR DESCRIPTION
**Pull request by fenuks**
This merge request adds `maven.vim` helper that extracts code for working with maven projects, adds detection for `mvnw` (and `mvnw.cmd` on Windows) wrapper. If wrapper is available, it is used to determine root of the maven project, and if it is executable, it is also used instead of global `mvn` command to generate classpath list.

Tests are included, based on analogous tests for `gradle.vim` helper.

### CODE REVIEW

**Comment by fenuks** [comment]
Hello, since there are no change requests, can this get merged? :)

**Comment by fenuks** [comment]
@w0rp Could you take look at this? I think it's good to go, changes had been reviewed, there are tests, and no conflicts (I've rebased it to sit on top of the latest upstream version, but since this pull request is closed, update is not shown).

**Comment by hsanson** [comment]
@fenuks can you reopen this PR? I cannot for some reason.  I will merge this if you manage to reopen it. I had tested this and works fine.

**Comment by fenuks** [comment]
Sadly, I cannot. I guess the fastest way will be opening a new PR.

**Pull request closed without merging**
