### PR TITLE
Use stdin instead of lint_file for nimcheck

### PR DESCRIPTION
**Pull request by tamago324**
This pull request gives you two options:
* `g:ale_lint_on_text_changed`
* `g:ale_lint_on_insert_leave`

I often use `g: ale_lint_on_insert_leave = 1`.
But nimcheck couldn't

### CODE REVIEW

**Comment by w0rp** [comment]
Are there any disadvantages to checking code via stdin, such as checking for type errors or anything with import lines, or does this just work?

**Comment by tamago324** [comment]
Cancel this pull request because the result was different when using A and not 😭

**Comment by RyanSquared** [comment]
That's strange. What was the difference? Could it possibly be a bug in nimcheck?

**Comment by tamago324** [comment]
I'll check if it's a bug in nimcheck

**Comment by tamago324** [comment]
Sorry for being very late.

I have asked [nimforum](https://forum.nim-lang.org/t/5534) a question.
As a result, it **should not be read from stdin**.
So this pull-request is closed.

Araq is also the author of nim.

**Comment by w0rp** [comment]
Okay, thanks for looking into this.

**Pull request closed without merging**
