### PR TITLE
Updated Luacheck to be project aware

### PR DESCRIPTION
**Pull request by Zulsorai**
Updated luacheck to be able to find and lint a directory containing _.luacheckrc_.
Luacheck is also able to parse the range of an error using the `--ranges` option.
When the option `lua_luacheck_lint_project` is disabled ale is able to return to the previous behavior of linting the buffer rather than the file on disk.

Tests and docs have been updated to reflect changes.

### CODE REVIEW

**Comment by RyanSquared** [comment]
```
ale_linters/lua/luacheck.vim:15 Trailing whitespace
```

Tests reported there's a trailing whitespace on the file. I'll be able to test this PR out soon, but can you get that fixed as well?

**Comment by Zulsorai** [comment]
That should be everything fixed.

**Comment by lithammer** [comment]
It would be nice to revive this. I'm running into this a lot that I have to `cd` into the correct directory first or else `luacheck` will complain.

**Comment by lithammer** [comment]
CC @Zulsorai @w0rp

**Pull request closed without merging**
