### PR TITLE
add autoflake fixer

### PR DESCRIPTION
**Pull request by circld**
- [x] implemented the fixer
- [x] added fixer tests
- [x] updated docs
    - [x] updated `ale-python.txt`
    - [x] updated `ale-supported-languages-and-tools.txt`
    - [x] updated `ale.txt`
    - [x] updated `supported-tools.md`

Super VimL novice here; got things working with a long monkey-see, monkey-do process. Nothing seems awry, so creating a PR.

The linting tests yelled at me, but as far as I can tell, they're not yelling about my changes. Do let me know if I'm off base on that 👍 

*Update* A bit confused about the appveyor tests failing... they're passing locally for me (at least when i redirect the output into a file):
image

### CODE REVIEW

**Comment by marcelomaia** [comment]
Hi! any updates? @circld

**Comment by paulgrow-octane** [comment]
Hey @marcelomaia 👋 

Not sure how to debug the appveyor errors-- as I pointed out in the PR description, all tests are passing locally. Any guidance would be appreciated.

**Comment by NikZak** [comment]
any updates on this?

**Comment by w0rp** [comment]
I think someone needs to re-open the pull request with the checks passing. Tag me if it comes back again. I haven't been looking at PRs too closely in recent months, but I'm starting to look a bit more often now.

**Comment by NikZak** [comment]
@w0rp, thanks! Just submitted pull #3779

**Pull request closed without merging**
