### PR TITLE
racket: support racket-langserver lsp

### PR DESCRIPTION
**Pull request by benknoble**
Not sure what tests are reasonable for an LSP linter. This worked for me after `raco pkg install racket-langserver`.

Notably, before I did that, the LSP didn't work (obviously), but I could see no error messages; only "executable check—success" for `racket`.

### CODE REVIEW

**Comment by hsanson** [comment]
Check ruby solargraph and eclipselsp test for example on how to write tests for a language server. In short:

1. Create directory and files that simulate a racket project in test-files. From what I see a racket project must have a init.rkt file, also I see it looks for the top most one so to test this you can create a directory tree with init.rkt files and test that the linter detects the correct project dir with AssertLSPProject.
2. Use AssertLSPLanguage, AssertLSPConfig, AssertLSPOptions, and AssertLinter to check that things are properly set.

**Comment by benknoble** [comment]
@hsanson done

**Review by hsanson — APPROVED** [review]
Thanks for the changes.

**Pull request merged**
