### PR TITLE
Adds support for gdscript3 lint with godot_server

### PR DESCRIPTION
**Pull request by rafaeldelboni**
Closes https://github.com/dense-analysis/ale/issues/1887

### CODE REVIEW

**Comment by rafaeldelboni** [comment]
Hello @w0rp could you check again?

**Comment by rcorre** [comment]
Should installing the godot server actually be a requirement? It would be nice if you could just provide a port to hook into the godot editor. Chances are you already have the editor running if you're editing GDScript.

**Comment by rafaeldelboni** [comment]
Do you have any reference where I can find how to accomplish this?

**Comment by rcorre** [comment]
The Godot editor exposes port 6008 as the language server port. This is configurable, so there should be a setting on the vim side as well.
Then ALE should point itself at that port. I think I posted an example in the gdscript3 thread, I can take a look tonight.

Then again, I'm new to LSP and my config wasn't 100% working, so I could be totally off on this.

**Comment by rafaeldelboni** [comment]
Oh yeah you right, but LSP will be released officially on version 3.2 right?

But I personally think that coc.nvim is a better candidate for this integration, I use it with Rust, Clojure and JavaScript LSP's and it works great WDYT?

**Comment by rafaeldelboni** [comment]
Oh yeah you right, but LSP will be released officially on version 3.2 right?

But I personally think that coc.nvim is a better candidate for this integration, I use it with Rust, Clojure and JavaScript LSP's and it works great WDYT?

**Comment by rcorre** [comment]
> Oh yeah you right, but LSP will be released officially on version 3.2 right?

Yes. I'd assumed that was what this PR was using, but now I see you're actually invoking the CLI.

I think this PR is still valuable then, as 3.2 isn't officially released, and I wasn't able to get linting to work with the server anyways. I might rename `gdscript3_godot_server_executable` to `gdscript3_godot_executable` though, as I don't think you'd actually need the server still (the godot editor has a `-s` and `--check-only` flag as well). Or does having the server make it faster?

> But I personally think that coc.nvim is a better candidate

One advantage of ALE is that it doesn't require node.js as a dependency, but I suppose that's not a huge deal.

**Comment by rcorre** [comment]
I stand corrected, the completions I thought I was getting from the LSP were actually from the gdscript3 plugin. The LSP isn't working at all for me right now.

**Comment by rcorre** [comment]
I see why the server is necessary now ... even with `--check-only -s` the regular `godot` executable will create a window. There is a `--no-window` flag but it supposedly only supports Windows.

**Comment by rafaeldelboni** [comment]
Thanks for the clarification, this code is just a port from @calviken's support for Syntastic, as I use Ale I tried my best to make the same work here.

I really wish @w0rp could just check this again haha, but I think I missed the eclipse and now only in some months he will come back here.
 
image

BTW, @rcorre looks like you play around a lot with Vim and Godot, do you have a portfolio where
I could check your games/studies/projects? I quite curious to know how your work flow with those tools looks like.

**Comment by rcorre** [comment]
Thanks for the interest @rafaeldelboni :)
I have two recent game jam projects [here](https://gitlab.com/rcorre/lichcraft) and [here](https://gitlab.com/rcorre/taxi-pilot), and some (neo)vim config [here](https://github.com/rcorre/dotfiles/tree/master/nvim). 

Unfortunately, you won't find much gdscript magic in there. Right now I don't really have the same editing experience with gdscript (completion/linting/ect.) that I do with other languages, which is why I've been watching these PRs :)

**Comment by rcorre** [comment]
I just checked out this PR and installed the Godot headless build, and I can confirm it works :+1: 

I created https://github.com/godotengine/godot-proposals/issues/198#issuecomment-549151838 to request `--no-window` support for Linux, but for now I think server/headless is our best bet.

Based on https://www.reddit.com/r/godot/comments/9s7exp/what_is_the_point_of_the_headless_and_server/, headless might actually be more appropriate than server for this use case, though they are pretty similar (I had to look up the difference).

I just did

```
:let g:ale_gdscript3_godot_server_executable = 'godot-headless'
```

**Comment by rafaeldelboni** [comment]
Hello @w0rp could you check again?
it's been 84 years

**Comment by nguyennb9** [comment]
Any update guys?

**Comment by rafaeldelboni** [comment]
Hello @nguyennb9, I just waiting for this commit get cherry-picked into version 3.2 to close this PR. Because it will render this pretty much useless, you will only need this plugin: https://github.com/rafaeldelboni/vim-gdscript3 and an LSP plugin of your choice, I personally use https://github.com/neoclide/coc.nvim and you will be good to go.

**Comment by nguyennb9** [comment]
> 
> 
> Hello @nguyennb9, I just waiting for this commit [godotengine/godot#35864](https://github.com/godotengine/godot/pull/35864)
> get cherry-picked into version 3.2 to close this PR. Because it will render this pretty much useless, you will only need this plugin: https://github.com/rafaeldelboni/vim-gdscript3 and an LSP plugin of your choice, I personally use https://github.com/neoclide/coc.nvim and you will be good to go.

It seems merged. I will give it a try, thank you.

**Comment by rafaeldelboni** [comment]
I'm super sad to close this without @w0rp proper evaluation, but since the new LSP mode is released this is not needed anymore. Anyway was a good experience to understand how to extend a Vim plugin.

Thanks.

**Comment by rcorre** [comment]
@rafaeldelboni if it makes you feel any better, I got a fair bit of use out of this in the meanwhile, and appreciate the work you put into it!

**Pull request closed without merging**
