### PR TITLE
Use the psalm executable with the LS option

### PR DESCRIPTION
**Pull request by greg0ire**
This is the simplest way of getting the psalm language server to run
now.

### CODE REVIEW

**Comment by greg0ire** [comment]
I'm really new to vimL and Vader and have little to no idea what I've been doing.

**Comment by muglug** [comment]
It was added 5 months ago - there's a slight risk of breaking changes, but (on the other hand) people _should_ be using the latest version of Psalm (which is still on the same major version as when the plugin was released)

**Comment by greg0ire** [comment]
Haha yeah! It's ripe now!

**Comment by w0rp** [comment]
I only just noticed that the `_executable` option isn't properly named. It should be `g:ale_php_psalm_executable`, instead of `g:ale_psalm_langserver_executable`. Update your settings now if you use that option. I'm about to change that.

**Pull request merged**
