### PR TITLE
Show errors and warnings for the 'smlnj' linter

### LINKED ISSUE #3953: SML: errors are no longer shown
## Information

VIM version:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 20 2021 11:42:42)
Included patches: 1-2269
```

Operating System: Ubuntu 20.04.2

## What went wrong

For Standard ML files, the results of linting no longer appear. Errors and warnings are no longer shown. This issue was introduced by #3860 / #1084

## Reproducing the bug
1.`vim myprog.sml`
2. Insert this invalid SML program:
   ```sml
   val _ = "abc" + 123
   val _ = 890 + "xyz"
   ```
3. `:w`
4. Observation: ALE does not display the linting results.

### :ALEInfo
```
 ALEInfo
 Current Filetype: sml
Available Linters: ['smlnj', 'smlnj_cm']
   Linter Aliases:
'smlnj_cm' -> ['smlnj-cm']
  Enabled Linters: ['smlnj', 'smlnj_cm']
  Ignored Linters: []
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_sml_smlnj_cm_file = '*.cm'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) sml
(finished - exit code 0) ['/bin/bash', '-c', 'sml < ''/tmp/vPjjmDK/1/myprog.sml''']

<<<OUTPUT STARTS>>>
Standard ML of New Jersey v110.79 [built: Sat Oct 26 12:27:04 2019]
- = stdIn:1.6-1.21 Error: operator and operand don't agree [overload conflict]
  operator domain: [+ ty] * [+ ty]
  operand:         string * [int ty]
  in expression:
    "abc" + 123
stdIn:2.5-2.20 Error: operator and operand don't agree [overload conflict]
  operator domain: [+ ty] * [+ ty]
  operand:         [+ ty] * string
  in expression:
    890 + "xyz"
-
<<<OUTPUT ENDS>>>
```

The relevant part is probably the output section. My guess is that there is a mismatch between the "filename" displayed by smlnj (i.e. `stdIn`) and the filename expected by ALE (`myprog.sml`).

@benknoble @hsanson

### PR DESCRIPTION
**Pull request by cwfoo**
Fixes #3953

### CODE REVIEW

**Comment by benknoble** [comment]
If @cwfoo can confirm their latest commit fixes the case I mentioned, then I approve.

**Comment by cwfoo** [comment]
@benknoble With the latest commit (i.e. "Change smlnj stdIn regex"), ale would show `Error: pattern and expression in val dec don't agree [tycon mismatch]` on the first line of `a.sml` in your `a.sml`/`b.sml` example.

**Comment by benknoble** [comment]
> @benknoble With the latest commit (i.e. "Change smlnj stdIn regex"), ALE would show `Error: pattern and expression in val dec don't agree [tycon mismatch]` on the first line of `a.sml` in your `a.sml`/`b.sml` example.

Great, than I think is ready to merge @hsanson 

> (I tried to test this yesterday, but I was bitten by a CM file that I left in my home directory some time ago. ALE really prefers CM!).

Well, that's because CM should be preferred :) actually, it's because _if_ there's a CM file, than there's likely no other way to correctly (try to) compile the file with SML/NJ—simply running it may not work if depends on modules declared in the CM file. OTOH, invoking it via CM is guaranteed to work. Granted, the CM file finder is a little… eager… in that it looks upwards and takes the first one it finds (even with multiple in the same directory). If there is a better way to handle this, suggestions are welcome.

**Review by hsanson — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
