### PR TITLE
diagnostics: support sending ALE output to Neovim's diagnostics API

### LINKED ISSUE #4005: [Neovim 0.6 Diagnostic API] ALE as the source of diagnostics to Neovim's new Diagnostic module
Hello ALE developers,

Spawning a new from [my comment](https://github.com/dense-analysis/ale/issues/3528#issuecomment-978915077) in #3528.

Neovim 0.6 was recently released with the main feature being the new [vim.diagnostic](https://neovim.io/doc/user/diagnostic.html) API. Previously diagnostics were a part of the native LSP client; but now it's an extracted stand-alone top level module.

Linting plugins such as [nvim-lint](https://github.com/mfussenegger/nvim-lint) and [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) are now using that API.

Can ALE also be enhanced to do the same? Does the architecture allow for that?

Aka, can ALE be a diagnostic source for display by another diagnostic engine? ALE has long had the option to be end-point for other diagnostic sources (aka CoC feeding it's diagnostics to ALE for display and navigation). But, this issue is wanting to go the other way; use ALE simply as the runner and then feed it's diagnostics to Neovim's new diagnostic module. The benefit for Neovim folks is a single source of display (signs, virtual-text, underlines) and a single set of mappings to navigate diagnostics.

Many thanks.

### PR DESCRIPTION
**Pull request by mathstuf**
Closes #4005

This resurrects #4135. I'll roll with it locally to test it out more (especially to see if that off-by-one is actually fixed or not). Other than test suite bits, the review comments from there have been addressed.

Pulling the TODO item from the original PR description:

- [x] Fix off by 1 issue reported by @daliusd below
- [x] Maybe good idea to add a test test_linting_sets_signs.vader or test_sign_placement.vader that tests ALE signs are disabled when neovim diagnostics are enabled.
- [x] Also maybe add a test to test_cursor_warnings.vader that tests cursor messages is not echoed when neovim diagnostics are enabled.
- [x] Figure out if it's OK to disable loclist/quickfix like we do currently
- [x] Fix issue with g:ale_virtualtext_cursor reported below

No tests yet (beyond updating the existing config one for the new option).

### CODE REVIEW

**Comment by w0rp** [comment]
If you can address the remaining TODO items here, I'll merge this one. I'm not working on it myself because I'm not a regular NeoVim user. (I'm waiting until NeoVim is named 1.0 and has some promises to not change default configuration for some time.)

**Comment by mathstuf** [comment]
I've been running with it for a while now and it works AFAICT. However, I still need to investigate these items to see if they're a problem yet. Not sure when I'll get time for that though.

> I'm waiting until NeoVim is named 1.0 and has some promises to not change default configuration for some time.

FWIW, I've only needed to set two things (that I should have been setting anyways) when migrating. That's other than the massive `s/vim/nvim/g` changes that needed to be done.

**Comment by bluz71** [comment]
> If you can address the remaining TODO items here, I'll merge this one. I'm not working on it myself because I'm not a regular NeoVim user. (I'm waiting until NeoVim is named 1.0 and has some promises to not change default configuration for some time.)

Neovim 1.0 could be years away.
Current stable release is 0.8.
Current development release is 0.9.
Since 0.5 release, Neovim is releasing a stable version (0.6, 0.7, 0.8) on a six month cadence (give or take).

0.5 --> 0.6 had major LSP API changes, basically a new module `vim.diagnostic` was extracted out of `vim.lsp`.

With respect to ALE, I am very confident that the APIs provided by Neovim that ALE would need to use to satisfy the PR are stable now and are **very unlikely** to change.

Best regards.

**Comment by w0rp** [comment]
> > If you can address the remaining TODO items here, I'll merge this one. I'm not working on it myself because I'm not a regular NeoVim user. (I'm waiting until NeoVim is named 1.0 and has some promises to not change default configuration for some time.)
> 
> Neovim 1.0 could be years away. Current stable release is 0.8. Current development release is 0.9. Since 0.5 release, Neovim is releasing a stable version (0.6, 0.7, 0.8) on a six month cadence (give or take).
> 
> 0.5 --> 0.6 had major LSP API changes, basically a new module `vim.diagnostic` was extracted out of `vim.lsp`.
> 
> With respect to ALE, I am very confident that the APIs provided by Neovim that ALE would need to use to satisfy the PR are stable now and are **very unlikely** to change.
> 
> Best regards.

That's good. I was speaking about my personal editor of choice. I'll be using Vim until Neovim hits 1.0.

**Comment by w0rp** [comment]
I and @Angelchev are fixing this now.

**Comment by w0rp** [comment]
@hsanson I'm going to disable ALE signs when sending messages to Neovim diagnostics is enabled, as there are ways of getting signs to appear for Neovim diagnostics. We can look into that later.

**Review by w0rp — APPROVED** [review]

**Pull request merged**
