### PR TITLE
Fix chktex highlighting wrong column when using tabs instead of spaces

### LINKED ISSUE #723: Wrong elements highlighted when using tabs instead of spaces (at least on LaTeX)
This seems a bit obvious but I did not find any related reports. I am suspecting I may have missed something or have something wrong in my .vimrc. Here is my .vimrc: https://github.com/jackgu1988/dotfiles/blob/master/vimrc

When I am using tabs on LaTeX and there is an error or a warning on a line, the wrong element is highlighted. For example here, the opening parenthesis bracket should have been highlighted because there is no space before it (line 88):

untitled

When I replace tabs with spaces it works just fine.
Is it my fault, or is it a bug?

### LINKED ISSUE #4712: Last update broke chktex linting for LaTeX it is needed to go back to reflog HEAD@{5} to have it back.
## Information

**VIM version**

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 16 2024 00:00:00)
Included patches: 1-31

Operating System:  Linux Fedora 38

## What went wrong

I use ALE installed via Plug. Today I updated it to the last release. This has broken the linting of LaTeX files with chktex. Better it works (checking :ALEInfo) but it is not copied in the lopen window and you can't navigate to the error.

To solve the issue I went back on the git repo with
    `git checkout HEAD@{number}`

The first one working is `HEAD@{5}`
Since the value 5 depends on  which revision you are on the one working has this extra information

  ``Previous HEAD position was 8922478 Add biome support for javascript (#4701)``
  ``HEAD is now at 9a23ec1 Ruff use json-lines output format (#4656)``

## Reproducing the bug

 1. update ALE plugin to the last version
 2.  be sure chktex is one the chosen linter for LaTeX with `let g:ale_linters = { 'latex' : ['chktex'] }` or similar in your .vimrc
 3. create a file test.tex with content
``\documentclass{article}``
``\begin{document}``
``    hello, () (``
``\end{document}``
  4. This files has at least two problems normally showed by chktex/ALE
        - line 4 W: No match found for '('. (15)
        - line 5 W: Number of '(' doesn't match the number of ')'! (17)
       But with the last revision they are not shown neither in the lopen window that is empty nor as annotations in the code nor as a symbol in the left column

### :ALEInfo
<details>
  <summary>Expand</summary>
  
  
  

 Current Filetype: tex
Available Linters: ['alex', 'chktex', 'cspell', 'lacheck', 'proselint', 'redpen', 'texlab', 'textlint', 'vale', 'writegood']
   Linter Aliases:
'writegood' -> ['write-good']
  Enabled Linters: ['chktex', 'proselint']
  Ignored Linters: []
 Suggested Fixers:
  'latexindent' - Indent code within environments, commands, after headings and within special code blocks.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'textlint' - Fix text files with textlint --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 
 Linter Variables:
let g:ale_tex_chktex_executable = 'chktex'
let g:ale_tex_chktex_options = '-I'
 
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 1
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%]% code:% %s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_info_default_mode = 'preview'
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'sh': ['shellcheck', 'shell'], 'cpp': ['gcc', 'clang'], 'text': ['vale', 'proselint', 'writegood'], 'latex': ['chktex', 'vale', 'proselint', 'writegood'], 'kotlin': ['kotlinc'], 'ada': ['gcc'], 'bash': ['shellcheck', 'bashate', 'shell'], 'ocaml': ['merlin'], 'erlang': ['dialyzer', 'erlc'], 'python': ['pylint', 'flake8', 'mypy'], 'tex': ['chktex', 'proselint'], 'pony': ['ponyc'], 'java': ['eclipselsp', 'checkstyle'], 'idris': ['idris'], 'scala': ['metals', 'fsc'], 'elixir': ['elixir', 'dialyxir', 'mix']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '[%linter%]% code:% %s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 1
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✘'
let g:ale_sign_info = 'I'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = 'S✘'
let g:ale_sign_style_warning = 'S▶'
let g:ale_sign_warning = '▶▶'
let g:ale_sign_highlight_linenrs = 0
let g:ale_type_map = {}
let g:ale_use_neovim_diagnostics_api = 0
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 'all'
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
 
  Command History:

(executable check - success) chktex
(finished - exit code 2) ['/usr/bin/bash', '-c', '''chktex'' -v0 -p stdin -q -s TabSize=1 -l ''.chktexrc'' -I < ''/tmp/vSLSNYi/4/prova.tex''']

<<<OUTPUT STARTS>>>
stdinTabSize=134TabSize=111TabSize=137TabSize=1You should avoid spaces after parenthesis.
stdinTabSize=182TabSize=179TabSize=118TabSize=1Use either `` or '' as an alternative to `"'.
stdinTabSize=134TabSize=110TabSize=115TabSize=1No match found for `('.
stdinTabSize=1144TabSize=11TabSize=117TabSize=1Number of `(' doesn't match the number of `)'!
<<<OUTPUT ENDS>>>

(executable check - success) proselint
(finished - exit code 1) ['/usr/bin/bash', '-c', 'proselint ''/tmp/vSLSNYi/5/prova.tex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 2) ['/usr/bin/bash', '-c', '''chktex'' -v0 -p stdin -q -s TabSize=1 -l ''.chktexrc'' -I < ''/tmp/vSLSNYi/13/prova.tex''']

<<<OUTPUT STARTS>>>
stdinTabSize=14TabSize=112TabSize=137TabSize=1You should avoid spaces after parenthesis.
stdinTabSize=14TabSize=111TabSize=115TabSize=1No match found for `('.
stdinTabSize=17TabSize=11TabSize=117TabSize=1Number of `(' doesn't match the number of `)'!
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/bash', '-c', 'proselint ''/tmp/vSLSNYi/14/prova.tex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 2) ['/usr/bin/bash', '-c', '''chktex'' -v0 -p stdin -q -s TabSize=1 -l ''.chktexrc'' -I < ''/tmp/vSLSNYi/15/prova.tex''']

<<<OUTPUT STARTS>>>
stdinTabSize=14TabSize=112TabSize=137TabSize=1You should avoid spaces after parenthesis.
stdinTabSize=14TabSize=111TabSize=115TabSize=1No match found for `('.
stdinTabSize=17TabSize=11TabSize=117TabSize=1Number of `(' doesn't match the number of `)'!
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/bin/bash', '-c', 'proselint ''/tmp/vSLSNYi/16/prova.tex''']

<<<NO OUTPUT RETURNED>>>

</details>

### PR DESCRIPTION
**Pull request by Jorengarenar**
<sup>Repetition of #4661, taking into account #4712</sup>

Fixes #723

chktex implemented [bug #56486: Allow setting options on the command line][1]
Thanks to that we can tell it to treat tab character as of one space width, i.e. one char.
That means, after we translate the output back to Vim columns, we get correct numbers.

[1]: https://savannah.nongnu.org/bugs/?56486

### CODE REVIEW

**Comment by hsanson** [comment]
The `-S` flag is not available in chktex 1.7.6 that is default in some distributions (e.g. Ubuntu) so this change breaks ALE for many users.  We have to make the `-S` flag optional based on version of chktex.

Or we can leave this out altogether since the `-S TabSize=8` seems to be the default and can be changed via `g:ale_tex_chktex_options` or `chktexrc` configuration.

**Comment by Jorengarenar** [comment]
I had added a check if the option is available

**Comment by Jorengarenar** [comment]
@hsanson I had added a check if the option is available

**Comment by hsanson** [comment]
After installing latest chktex 1.7.8 and doing several test I was able to understand what this PR tries to do. I made some modifications (see diff below) that you can add to this PR to improve it:

1. Use async RunWithVersionCheck() instead of calling blocking system() function.
2. Use &tabstop option instead of hardcoded `1` so it works with different vim configurations.
3. Honor .chktexrc file over hardocded `-S TabSize` if it exists.
4. Add tests and update current ones to test command arguments based on chktex version.

Save the following diff in a file and use git-apply to apply it:

```diff
diff --git a/ale_linters/tex/chktex.vim b/ale_linters/tex/chktex.vim
index dd064127..ca336326 100644
--- a/ale_linters/tex/chktex.vim
+++ b/ale_linters/tex/chktex.vim
@@ -4,22 +4,28 @@
 call ale#Set('tex_chktex_executable', 'chktex')
 call ale#Set('tex_chktex_options', '-I')
 
-function! ale_linters#tex#chktex#GetCommand(buffer) abort
+function! ale_linters#tex#chktex#GetExecutable(buffer) abort
+    return ale#Var(a:buffer, 'tex_chktex_executable')
+endfunction
+
+function! ale_linters#tex#chktex#GetCommand(buffer, version) abort
     let l:options = ''
 
     " Avoid bug when used without -p (last warning has gibberish for a filename)
     let l:options .= ' -v0 -p stdin -q'
 
-    " Avoid bug of reporting wrong column when using tabs (issue #723)
-    if system('chktex -S') !~? 'invalid option'
-        let l:options .= ' -S TabSize=1'
-    endif
-
     " Check for optional .chktexrc
     let l:chktex_config = ale#path#FindNearestFile(a:buffer, '.chktexrc')
 
     if !empty(l:chktex_config)
         let l:options .= ' -l ' . ale#Escape(l:chktex_config)
+    else
+        " If no configuration file is found try to set TabSize value based
+        " on buffer tabstop (#723). Note -S option is available on chktex
+        " 1.7.7+.
+        if ale#semver#GTE(a:version, [1, 7, 7])
+            let l:options .= ' -S TabSize=' . &tabstop
+        endif
     endif
 
     let l:options .= ' ' . ale#Var(a:buffer, 'tex_chktex_options')
@@ -49,7 +55,12 @@ endfunction
 
 call ale#linter#Define('tex', {
 \   'name': 'chktex',
-\   'executable': {b -> ale#Var(b, 'tex_chktex_executable')},
-\   'command': function('ale_linters#tex#chktex#GetCommand'),
+\   'executable': function('ale_linters#tex#chktex#GetExecutable'),
+\   'command': {buffer -> ale#semver#RunWithVersionCheck(
+\       buffer,
+\       ale_linters#tex#chktex#GetExecutable(buffer),
+\       '%e --version',
+\       function('ale_linters#tex#chktex#GetCommand'),
+\   )},
 \   'callback': 'ale_linters#tex#chktex#Handle'
 \})
diff --git a/test/linter/test_tex_chktex.vader b/test/linter/test_tex_chktex.vader
index 94ce0d49..1e037004 100644
--- a/test/linter/test_tex_chktex.vader
+++ b/test/linter/test_tex_chktex.vader
@@ -1,21 +1,44 @@
 Before:
   call ale#assert#SetUpLinterTest('tex', 'chktex')
 
+  GivenCommandOutput ['ChkTeX v1.7.6 - Copyright 1995-96 Jens T. Berger Thielemann']
+
 After:
   call ale#assert#TearDownLinterTest()
 
 Execute(The default command should be correct):
-  AssertLinter 'chktex',
+  AssertLinter 'chktex', [
+  \ ale#Escape('chktex') . ' --version',
   \ ale#Escape('chktex')
-  \   . ' -v0 -p stdin -q -S TabSize=1'
-  \   . ' -I'
+  \   . ' -v0 -p stdin -q'
+  \   . ' -I',
+  \]
+
+  " The version check should be cached.
+  GivenCommandOutput []
+  AssertLinter 'chktex', [
+  \ ale#Escape('chktex')
+  \   . ' -v0 -p stdin -q'
+  \   . ' -I',
+  \]
+
+  " Try newer version
+  call ale#semver#ResetVersionCache()
+  GivenCommandOutput ['ChkTeX v1.7.8 - Copyright 1995-96 Jens T. Berger Thielemann']
+  AssertLinter 'chktex', [
+  \ ale#Escape('chktex') . ' --version',
+  \ ale#Escape('chktex')
+  \   . ' -v0 -p stdin -q'
+  \   . ' -S TabSize=' . &tabstop
+  \   . ' -I',
+  \]
 
 Execute(The executable should be configurable):
   let g:ale_tex_chktex_executable = 'bin/foo'
 
   AssertLinter 'bin/foo',
   \ ale#Escape('bin/foo')
-  \   . ' -v0 -p stdin -q -S TabSize=1'
+  \   . ' -v0 -p stdin -q'
   \   . ' -I'
 
 Execute(The options should be configurable):
@@ -23,5 +46,5 @@ Execute(The options should be configurable):
 
   AssertLinter 'chktex',
   \ ale#Escape('chktex')
-  \   . ' -v0 -p stdin -q -S TabSize=1'
+  \   . ' -v0 -p stdin -q'
   \   . ' --something'
```

**Comment by Jorengarenar** [comment]
@hsanson 
The fix of issue #723 is precisely to set TabSize to 1; no other value makes sense here, because tab is one character and that's how we want chktex to treat it, so we get correct column number in Vim.

**Comment by hsanson** [comment]
@Jorengarenar after further testing it seems you are correct and TabSize must be fixed to `1`.  You can modify the diff to replace `&tabstop' with `1` in the linter and test files.

**Review by hsanson — APPROVED** [review]
Thanks for the work and patience.

**Pull request merged**
