### PR TITLE
Mypy: try to find folder containing mypy.ini to use as cwd.

### LINKED ISSUE #2383: Mypy plugin does not choose correct cwd
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 30 2018 10:53:32)
Included patches: 1-551

Operating System: Ubuntu 18.10

## What went wrong

opening an new issues as suggested over in #363 thread.  issue in brief is that vim-ale isn't choosing the "right" path to run `mypy` from.  Repo below.

## Reproducing the bug

* project base folder contains mypy.ini
* but it does not contain any of the other files that mark a folder as being the right "python root" (no pytest.ini, setup.cfg, etc)
* other subfolders do contain such files, eg the `src` subfolder (which has setup.py), or a `tests` subfolder (which has pytest.ini)
* vim is correctly configured to use the project's virtualenv, which has mypy installed.

what happens: ale finds the virtualenv mypy just fine, but it cds to a different directory (either a parent or a child, depending on which file is being linted, but one containing a pytest.ini in either case) when it runs mypy, which means the mypy.ini is ignored.

```
👉  tree                            
.
├── mypy.ini
├── requirements.txt
├── src
│   ├── allocation
│   │   ├── model.py
│   │   ├── ...
│   └── setup.py
└── tests
    ├── conftest.py
    ├── pytest.ini
    ├── ...
    └── unit
        ├── ...
        └── test_services.py
```

a possible fix might be to override function! ale#python#FindProjectRoot in favour of "whatever the location of mypy.ini is" for choosing the cwd of calls to mypy?

### :ALEInfo

```

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'pycodestyle', 'pylint']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:

let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%s'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 127) ['/usr/bin/zsh', '-c', '''/home/harry/workspace/python-leap/book/code/.venv/bin/pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']

<<<NO OUTPUT RETURNED>>>

(started) ['/usr/bin/zsh', '-c', '''flake8'' --format=default --stdin-display-name ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' - < ''/tmp/vXKnjlN/323/test_services.py''']
(started) ['/usr/bin/zsh', '-c', 'cd ''/home/harry/workspace/python-leap/book/code/tests'' && ''/home/harry/workspace/python-leap/book/code/.venv/bin/mypy'' --show-column-numbers  --shadow-file ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' ''/tmp/vXKnjlN/324/test_services.py'' ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']
(started) ['/usr/bin/zsh', '-c', '''/home/harry/workspace/python-leap/book/code/.venv/bin/pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']
(finished - exit code 127) ['/usr/bin/zsh', '-c', '''flake8'' --format=default --stdin-display-name ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' - < ''/tmp/vXKnjlN/325/test_services.py''']

<<<OUTPUT STARTS>>>
zsh:1: /usr/local/bin/flake8: bad interpreter: /usr/local/bin/python3: no such file or directory
<<<OUTPUT ENDS>>>

(finished - exit code 127) ['/usr/bin/zsh', '-c', 'cd ''/home/harry/workspace/python-leap/book/code/tests'' && ''/home/harry/workspace/python-leap/book/code/.venv/bin/mypy'' --show-column-numbers  --shadow-file ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' ''/tmp/vXKnjlN/326/test_services.py'' ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 127) ['/usr/bin/zsh', '-c', '''/home/harry/workspace/python-leap/book/code/.venv/bin/pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']

<<<NO OUTPUT RETURNED>>>

(started) ['/usr/bin/zsh', '-c', '''flake8'' --format=default --stdin-display-name ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' - < ''/tmp/vXKnjlN/327/test_services.py''']
(started) ['/usr/bin/zsh', '-c', 'cd ''/home/harry/workspace/python-leap/book/code/tests'' && ''/home/harry/workspace/python-leap/book/code/.venv/bin/mypy'' --show-column-numbers  --shadow-file ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' ''/tmp/vXKnjlN/328/test_services.py'' ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']
(started) ['/usr/bin/zsh', '-c', '''/home/harry/workspace/python-leap/book/code/.venv/bin/pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''flake8'' --format=default --stdin-display-name ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' - < ''/tmp/vXKnjlN/329/test_services.py''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 127) ['/usr/bin/zsh', '-c', 'cd ''/home/harry/workspace/python-leap/book/code/tests'' && ''/home/harry/workspace/python-leap/book/code/.venv/bin/mypy'' --show-column-numbers  --shadow-file ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' ''/tmp/vXKnjlN/330/test_services.py'' ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 127) ['/usr/bin/zsh', '-c', '''/home/harry/workspace/python-leap/book/code/.venv/bin/pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']

<<<NO OUTPUT RETURNED>>>

(started) ['/usr/bin/zsh', '-c', '''flake8'' --format=default --stdin-display-name ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' - < ''/tmp/vXKnjlN/331/test_services.py''']
(started) ['/usr/bin/zsh', '-c', 'cd ''/home/harry/workspace/python-leap/book/code/tests'' && ''/home/harry/workspace/python-leap/book/code/.venv/bin/mypy'' --show-column-numbers  --shadow-file ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' ''/tmp/vXKnjlN/332/test_services.py'' ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']
(executable check - success) pylint
(started) ['/usr/bin/zsh', '-c', '''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''flake8'' --format=default --stdin-display-name ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' - < ''/tmp/vXKnjlN/333/test_services.py''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', 'cd ''/home/harry/workspace/python-leap/book/code/tests'' && ''/home/harry/workspace/python-leap/book/code/.venv/bin/mypy'' --show-column-numbers  --shadow-file ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py'' ''/tmp/vXKnjlN/334/test_services.py'' ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']

<<<OUTPUT STARTS>>>
unit/test_services.py:1:1: error: No library stub file for module 'pytest'
unit/test_services.py:1:1: note: (Stub files are from https://github.com/python/typeshed)
unit/test_services.py:4:1: error: Cannot find module named 'allocation'
unit/test_services.py:4:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
<<<OUTPUT ENDS>>>

(finished - exit code 127) ['/usr/bin/zsh', '-c', '''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/harry/workspace/python-leap/book/code/tests/unit/test_services.py''']

<<<NO OUTPUT RETURNED>>>
```

in the above, the errors, like "no library stuf file for module pytest" and "cannot find module allocation" do *not* appear if I manually run mypy from the project root, because there are fixes in mypy.ini in that folder.

### PR DESCRIPTION
**Pull request by hjwp**
attempts to fix #2383 

no tests i'm afraid (yet? will see what i can do.  i don't know vimscript...)

### CODE REVIEW

**Comment by johnor** [comment]
@hjwp Are you going to continue to work on this PR? I have tested it and it solves #2383. Would be great if we could get it merged.

**Comment by hjwp** [comment]
ok, am giving it a go now.

**Comment by hjwp** [comment]
OK i think the test work.  I couldn't figure out how to use `ale#path#FindNearestFile`, or at least, i tried using it, but i couldn't figure out how to derive the containing folder, given a full path to a file.  But what we have now works...

**Comment by hjwp** [comment]
:tada: hooray! and no need to apologise.  happy new year!

**Pull request merged**
