### PR TITLE
Add jsonnetfmt linter and fixer

### PR DESCRIPTION
**Pull request by itkq**
[Jsonnet](https://jsonnet.org/) is a data template language, which becomes more popular today. [jsonnetfmt](https://jsonnet.org/learning/tools.html) command is a built-in formatter.

### CODE REVIEW

**Comment by 0xMH** [comment]
I guess the is a valid PR that should have been passed otherwise. Can someone shed some lights on what needs to be changed to merge this?

**Comment by itkq** [comment]
Thanks for noticing me. I've been using this change in my forked branch and it works well for me. But I'd like to see you incorporate the changes into upstream if it's possible.

@w0rp Could you take a look at it?

**Comment by SuperSandro2000** [comment]
bump

**Comment by trevorwhitney** [comment]
another bump, I'm using @itkq's fork and it's working. I did need to change the regex for errors a bit, but I wonder if that's a versioning issue? either way I'm happy to help get this merged, what else needs to be done?

**Comment by hsanson** [comment]
I am afraid this PR cannot be reopen because the master branch has changed significantly.  A new branch must be created from current master branch and while doing so would be great to update the tests to use "AssertFixer" that is the new way to test the fixer command callbacks (see `:h ale-development-fixer-tests`).

**Comment by itkq** [comment]
I haven't been writing jsonnnet recently so I don't have much motivation to get merge this PR. Now I understand the situation and I'd be happy if @trevorwhitney takes over this task!

**Pull request closed without merging**
