### PR TITLE
Add protolint linter and fixer

### PR DESCRIPTION
**Pull request by yoheimuta**
This PR adds [protolint](https://github.com/yoheimuta/protolint) as a linter and a fixer for Protocol Buffer.

### CODE REVIEW

**Comment by yoheimuta** [comment]
That works like the following.

vim-protolint-2

**Comment by yoheimuta** [comment]
@hsanson ( @w0rp ) Thank you for your review!
Is something lacking in this pull request still?

**Comment by hsanson** [comment]
Be patient until the PR is merged by someone with merge privileges. I myself have several PR's waiting to be merged.

**Comment by yoheimuta** [comment]
Thank you for your information.
I understand.

**Comment by wwuck** [comment]
@hsanson How do we reopen this PR and get it merged?  It would be nice to have automatic support for protolint inside ale.

**Comment by hsanson** [comment]
@wwuck thanks for the reminder.

**Pull request merged**
