### PR TITLE
Add ALEGoToImplementation

### LINKED ISSUE #2550: C/C++ ALEGoToDeclaration (or ALEGoToImplementation)
Since there is `ALEGoToDefinition`, maybe there should be an `ALEGoToDeclaration` for languages (like C/C++) which have those separately (e.g. the `ALEGoToDefinition` should go to the right place in the `*.h` file, and the `ALEGoToDeclaration` should go to the right place in the corresponding `*.cpp` file.)

FWIW, YouCompleteMe has a similar feature:
https://github.com/Valloric/YouCompleteMe#the-gotodeclaration-subcommand

### PR DESCRIPTION
**Pull request by sak96**
## Why the Pull Request?

As per [ale dev philosophy](https://github.com/dense-analysis/ale/wiki/ALE-Development-Philosophy#important-principles-for-ale-code) point 8 this feature is added to allow going to implementation. Newer languages like golang have interface whichis implementation in different location. This feature may also be useful for other languages as mentioned in #2550.

## Tasks
- [x] get feature working
- [x] fix coding standards issue
- [x] write test cases for code
- [x] Add documentation

## References
- [LSP GotoImplementation](https://microsoft.github.io/language-server-protocol/specification#textDocument_implementation)
- [TSsever GotoImplementation](https://github.com/microsoft/TypeScript/blob/ce487e4fd37cd8715191e5f641c08a120de90521/lib/protocol.d.ts#L21)

### CODE REVIEW

**Comment by sak96** [comment]
To test this in go 
### requirement
gopls installed.
### Files
---
*go.mod*
```go
module inter
go 1.18
````
---
inter.go
```go
package inter

type IFlyer interface {
	fly() string
}

type Bird struct {
	Name string
}

func (b *Bird) fly() string {
	return "Flying..."
}
```

running `:ALEGoToImplementation` on fly on line 4 will jump you to line 11 fly implementation.

**Comment by sak96** [comment]
Feature in action
gotoimpl

**Comment by sak96** [comment]
@hsanson 

if i am not wrong appveyor/pr is running same thing as github CI.
why are there two of them. is it some security thing?

**Comment by hsanson** [comment]
@sak96  yes, appveyor and github actions are both CI tools.  Before we used appveyor for Windows tests and TravisCI for linux/mac but migrated not long ago to Github Actions.  Unfortunatelly all attempts to make the tests run in Windows using Github actions failed so we left Appveyor for it.  As the say goes if not broken don't fix it:

  - https://github.com/dense-analysis/ale/pull/3554

**Review by hsanson — APPROVED** [review]
Thanks for the work... it looks good to me.  I am not expert in LSP so all I can do is check the code looks reasonable and that it does not breaks things for the LSP servers I use.

**Pull request merged**
