### PR TITLE
Zig support using zls.

### PR DESCRIPTION
**Pull request by CherryMan**

### CODE REVIEW

**Comment by CherryMan** [comment]
Can't seem to figure out why the CI is failing, the headings seem correct when I test them.

**Comment by CherryMan** [comment]
Closes #2484.

**Comment by hsanson** [comment]
@CherryMan in the `doc/ale.txt` file add one blank line after line 2680, that is after the zls entry you added.  After adding the line you can run the `test//script/check-toc` script directly to see if the error is gone.

**Comment by CherryMan** [comment]
@hsanson Thanks, that worked.

**Comment by dps910** [comment]
Hi, I am unable to get zls working even though I have it installed. I can run it from terminal just fine, but ALE does not recognise it. Here are my linters:
```
let g:ale_linters = {
    \ 'javascript': ['tsserver'],
    \ 'typescript': ['tsserver'],
    \ 'yaml': ['yamllint'],
    \ 'go': ['gopls'],
    \ 'python': ['flake8'],
    \ 'zig': ['zls'],
    \ }
```
But if I open a file with extension `.zig`, here is what ALEInfo shows me:
```
Available Linters: []
  Enabled Linters: []
  Ignored Linters: []
```

**Comment by CherryMan** [comment]
@dps910 I suspect that without `Plug 'ziglang/zig.vim'`, `filetype` wasn't being set to `zig` as it's supposed to, and so this part of the plugin wasn't being loaded. This is intentional.

**Pull request merged**
