### PR TITLE
Python support poetry

### PR DESCRIPTION
**Pull request by unc0**
Add poetry automatic detect support to python linters and black fixer.
https://github.com/dense-analysis/ale/issues/1656#issuecomment-414760077

### CODE REVIEW

**Comment by giodamelio** [comment]
This is just what I was looking for. Thanks for sparing me the work @unc0!

Until is lands and is released though, here is the workaround I have been using.

```
let g:ale_python_black_executable = 'poetry'
let g:ale_python_black_options = 'run black'
```

**Comment by gcoakes** [comment]
Is there something specific blocking this?

**Comment by ethan-leba** [comment]
bumping this PR, would love to have support for poetry in ALE!

**Comment by stefansedich** [comment]
Another bump for this PR!

**Comment by wbthomason** [comment]
Is there anything that I/the community could do to move this PR along to the merge stage? This would be great to have; I've had to start disabling ALE for Python in Poetry projects just because of the number of spurious errors.

**Comment by redbmk** [comment]
> This is just what I was looking for. Thanks for sparing me the work @unc0!
> 
> Until is lands and is released though, here is the workaround I have been using.
> 
> ```
> let g:ale_python_black_executable = 'poetry'
> let g:ale_python_black_options = 'run black'
> ```

This was working great for me until I edited a file in a project that wasn't using poetry. When I did that the file was wiped out and changed to look like:

> 
> [RuntimeError]
> Poetry could not find a pyproject.toml file in /path/to/project or its parents

I could put a `pyproject.toml` file in my home folder, but that will also run black in projects that aren't configured for it.

Another workaround I found that works for me is to set poetry to create a virtualenv in the project's root so that ALE can find it in the project's `.venv` folder, then just keep the ALE settings as default. I had to delete the virtualenvs that had already been created for that to work:

```bash
poetry config virtualenvs.in-project true

# for a mac, not cross-platform
rm -rf ~/Library/Caches/pypoetry/virtualenvs/*

# then need to reinstall run for any existing poetry projects
poetry install
```

There's probably a better, cross-platform way to remove existing poetry virtualenvs.

That said, would love to see ALE support poetry out of the box even if the virtualenv is outside the project's root.

**Comment by ecly** [comment]
This would certainly be a wonderful addition, considering the growing popularity of `poetry`.

**Comment by ecly** [comment]
This would certainly be a wonderful addition, considering the growing popularity of `poetry`.

**Comment by nogweii** [comment]
Could this be reopened and get a second look?

**Comment by w0rp** [comment]
I think I missed this one before. There's a bunch of conflicts with this one now. @unc0 if you want to fix this, or if anyone else wants to open another PR that fixes the merge conflicts, I'll have a look.

**Comment by w0rp** [comment]
I'll close this until the conflicts can be fixed.

**Comment by danielroseman** [comment]
Hi @w0rp I had a go at fixing all these conflicts in #3834

**Pull request closed without merging**
