### PR TITLE
add b:undo_ftplugin

### PR DESCRIPTION
**Pull request by benknoble**
Close https://github.com/dense-analysis/ale/issues/4624 by adding `b:undo_ftplugin` to all files.

### CODE REVIEW

**Review by w0rp — APPROVED** [review]
Nice addition!

Cheers! 🍻

**Comment by w0rp** [comment]
Have a look at the CI issues.

**Comment by benknoble** [comment]
I see

    (8/9) [EXECUTE] (X) Jobs did not complete on time!

Could it be spurious timeout? Might just need re-run. I assume that failure also cancelled the other test runners.

**Comment by w0rp** [comment]
Tests passed locally so I just forced this through, and I'll fix it from there.

Cheers! :beers:

**Pull request merged**
