### PR TITLE
Add dart analysis server to linter

### LINKED ISSUE #1005: Add support for Dart analysis server
Related issue: https://github.com/w0rp/ale/issues/1002 (dartanalyzer is too slow)

The analysis server is about 10 times faster than the command-line analyzer (hence latency should go from 9+s to ~0.9s).
Specifications of the protocol: https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html

Recommendation initially given by @wilkerson at https://github.com/dart-lang/sdk/issues/31108#issuecomment-336928324

### PR DESCRIPTION
**Pull request by nelsyeung**
Add Dart analysis_server to linter. Closes #1005

### CODE REVIEW

**Review by guildem — DISMISSED** [review]

**Review by RRethy — DISMISSED** [review]
I've been using it locally and it's working well for me.

**Comment by bluz71** [comment]
I just tested this PR locally.

Functionally it works great.

However, I am receiving the following noise in the command line area:

Dart_Analysis_Server

`Unknown method textDocument/didSave`

This appears every time I hit save, which is my trigger for a lint to occur.

I am using Flutter `v1.12.13+hotfix.8`.

It would be highly desirable to silently consume this particular message, it gets annoying fast.

Best regards.

**Comment by RRethy** [comment]
I'm also seeing that, part of my config was hiding it so I didn't notice previously.

**Comment by RRethy** [comment]
https://github.com/sublimelsp/LSP/issues/550 this issue describes it.

**Comment by bluz71** [comment]
> I'm also seeing that, part of my config was hiding it so I didn't notice previously.

How did you hide it? This PR probably should probably include that workaround.

**Comment by bluz71** [comment]
These issues are relevant:

- [LSP: Unknown method textDocument/didSave](https://github.com/dart-lang/sdk/issues/36464)

- [Don't send textDocument/didSave unless server advertises support for it](https://github.com/natebosch/vim-lsc/issues/164)

Correct me if I am wrong, but I think ALE may be sending `textDocument/didSave` to the Dart Analysis Server even after the server says it doesn't support `textDocumentSync > save`.

I suspect ALE LSP code needs to be refined to not send `textDocument/didSave` after the server initially indicates it doesn't support that operation.

As it stands at the moment, every Dart file save is triggering this alert which distracts from genuine lint messages.

**Comment by nelsyeung** [comment]
@bluz71 Do you think it's worth raising this as a separate issue and create a fix in a separate PR?

**Comment by bluz71** [comment]
Yes, it is a separate issue. It should not hold this up.

I was going to create a new issue today, but got distracted with other stuff. I will do so soon.

**Comment by bluz71** [comment]
New issue,  #3207, spawned about the `didSave` issue.

This PR can be merged independent of that. This looks ready now.

**Review by hwasoocho — DISMISSED** [review]

**Comment by nelsyeung** [comment]
@w0rp This is certainly not stale and would love to be merged asap.

**Comment by bluz71** [comment]
Seconded. Looking forward to seeing this merged.

**Comment by nelsyeung** [comment]
@w0rp bump

**Comment by bluz71** [comment]
I agree, not stale.

**Comment by nelsyeung** [comment]
I'm not gonna lose this battle to a bot!

**Comment by lukaszo** [comment]
Hello @nelsyeung 

please consider updating your patch with this tiny patch:

```diff
11c11
<     return !empty(l:pubspec) ? fnamemodify(l:pubspec, ':h:h') : ''
---
>     return !empty(l:pubspec) ? fnamemodify(l:pubspec, ':h:h') : '.'
```
I've just changed it to return current dir when pubspec is not available.  In this way it will support also standalone files.

**Review by RRethy — APPROVED** [review]

**Review by guildem — APPROVED** [review]

**Comment by matsp** [comment]
Anything missing?

**Comment by nelsyeung** [comment]
> Anything missing? Out of the box support would be really great 👍

Nope, just waiting for review and merge.

**Comment by matsp** [comment]
@hwasoocho Can you please review this PR?

**Comment by matsp** [comment]
@RRethy @guildem Can someone else review this PR?

**Review by guildem — APPROVED** [review]

**Review by hsanson — CHANGES_REQUESTED** [review]
Missing tests. Check the test/command_callbak folder for examples on how to write tests for command callbacks.

**Comment by nelsyeung** [comment]
@hsanson Command callback tests added

**Review by hsanson — DISMISSED** [review]

**Comment by hsanson** [comment]
ALE migrated from Travis to Github Actions (see #3548) so it is necessary to rebase this PR from latest master branch to trigger the required checks.

```
# Add dense-analysis as remote upstream on your local fork. Not 
# needed if already added.
git remote add upstream https://github.com/dense-analysis/ale.git

# Sync your local master with upstream master
git checkout master
git fetch upstream master
git merge upstream/master

# Rebase the PR branch with master
git checkout my-branch-name
git rebase master   # Fix any conflicts you may have

# Force push the updated PR branch to origin to trigger the checks
git push -f origin my-branch-name
```

**Review by hsanson — APPROVED** [review]
Ready to go, thanks.

**Pull request merged**
