### PR TITLE
Support selecting the first completion option / Remove 'noselect' from completeopts

### PR DESCRIPTION
**Pull request by rouge8**
This patch removes `noselect` from the default `completeopts`. This should no longer be necessary thanks to 25b572b3bf3cc0229ed836eb3fa80c4c74f2c247, because the `<C-p>` added to the map will deselect the first entry.

Combined with something like this in your `~/.vimrc`:

```vim
function! RemapAleCompletion()
  iunmap <Plug>(ale_show_completion_menu)
  inoremap <silent> <Plug>(ale_show_completion_menu) <C-x><C-o>
endfunction

augroup remap_ale_completion
  autocmd!
  autocmd VimEnter * call RemapAleCompletion()
augroup END
```

This can address #3433.

### CODE REVIEW

**Comment by MeTheFlea** [comment]
> ```viml
> function! RemapAleCompletion()
>   iunmap <Plug>(ale_show_completion_menu)
>   inoremap <silent> <Plug>(ale_show_completion_menu) <C-x><C-o>
> endfunction
> 
> augroup remap_ale_completion
>   autocmd!
>   autocmd VimEnter * call RemapAleCompletion()
> augroup END
> ```

I'm a bit of a vimscript novice but this snippet doesn't seem to work, since `<Plug>(ale_show_completion_menu)` doesn't seem to be set by the time `VimEnter * call RemapAleCompletion()` is executed. It seems like `<Plug>(ale_show_completion_menu)` is only set after the first time `ALEComplete` is called, and I'm not sure if there's an `autocmd` moment where I can automatically override it once it gets set. However, calling `RemapAleCompletion()` manually after doing `:ALEComplete` once does seem to provide the behaviour I originally wanted in #3433.

**Comment by rouge8** [comment]
> I'm a bit of a vimscript novice but this snippet doesn't seem to work, since `<Plug>(ale_show_completion_menu)` doesn't seem to be set by the time `VimEnter * call RemapAleCompletion()` is executed. It seems like `<Plug>(ale_show_completion_menu)` is only set after the first time `ALEComplete` is called, and I'm not sure if there's an `autocmd` moment where I can automatically override it once it gets set. However, calling `RemapAleCompletion()` manually after doing `:ALEComplete` once does seem to provide the behaviour I originally wanted in #3433 for the rest of the vim session.

I think I can reproduce what you're seeing when I *don't* use `let g:ale_completion_enabled = 1`. In that case, I believe this PR plus this function fixes #3433:

```vim
function! RemapAleCompletion()
  " Load autoload/ale/completion.vim and the <Plug>(ale_show_completion_menu) mapping
  ALEComplete
  " or:
  " call ale#completion#GetCompletions('ale-manual')

  iunmap <Plug>(ale_show_completion_menu)
  inoremap <silent> <Plug>(ale_show_completion_menu) <C-x><C-o>
endfunction

augroup remap_ale_completion
  autocmd!
  autocmd VimEnter * call RemapAleCompletion()
augroup END
```

**Review by w0rp — CHANGES_REQUESTED** [review]
I think instead of this change, we need a separate `Plug` mapping for manual completion (`ale-manual`) so we don't send `C-p` to back out of selecting the first item. This can be done by adding an argument to `s:OpenCompletionMenu` to change which `Plug` key it sends. We can't select the first item from automatic completion as it will interrupt typing, but we can when you open the completion menu through a keybind.

**Comment by rouge8** [comment]
> I think instead of this change, we need a separate `Plug` mapping for manual completion (`ale-manual`) so we don't send `C-p` to back out of selecting the first item. This can be done by adding an argument to `s:OpenCompletionMenu` to change which `Plug` key it sends. We can't select the first item from automatic completion as it will interrupt typing, but we can when you open the completion menu through a keybind.

I actually use this with automatic completion. The `noinsert` ensures it doesn't insert the selected item unless I request it with `C-y`.

**Comment by w0rp** [comment]
I'm gonna replace this with an alternate patch which respects the value of `completeopt`, so you'll get `noselect` if you have your options configured that way, otherwise you won't.

**Pull request closed without merging**
