### PR TITLE
Fix stylelint not obeying project-specific rules

### LINKED ISSUE #3271: stylelint is applying global .stylelintrc, not local
## Information

**VIM version**

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug  2 2020 00:45:48)
macOS version
Included patches: 1-1350

Operating System: macOS 10.15.6

## What went wrong

stylelint in :ALEFix is applying the "global" .stylelintrc in my home directory, rather than the local .stylelintrc.json in my project directory.

## Reproducing the bug

1. I have a project-specific .stylelintrc
2. I run :ALEFix on a CSS file with just the following options:
   ```
	let g:ale_fixers = {}
	let g:ale_fixers['css'] = [
				\   'stylelint',
				\ ]
   ```
3. ALE applies the settings from my global .stylelintrc

### :ALEInfo

> `(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/Users/MYNAME/project/scss'' && ''/Users/MYNAME/project/node_modules/stylelint/bin/stylelint.js'' ''/Users/MYNAME/tmp/v764s1s/7/index.scss'' --fix']`

### PR DESCRIPTION
**Pull request by jsit**
Closes #3271

### CODE REVIEW

**Comment by jsit** [comment]
@w0rp, Can I please get another look at this? Thanks.

**Review by hsanson — COMMENTED** [review]
Looks good. Thanks.

**Comment by jsit** [comment]
@hsanson Thanks; fixed the conflicts.

**Review by hsanson — APPROVED** [review]
Thanks for fixing the conflicts.

**Pull request merged**
