### PR TITLE
feat: Adds variable to use custom config file with Elixir Credo

### PR DESCRIPTION
**Pull request by Thau**
Reopened version of #3331 because stale-bot closed it, including @w0rp's suggestions.

Adds g:ale_elixir_credo_config_file to allow users to use a custom configuration file for the checks. Motivation is my company using a centralised configuration file for all of our Elixir projects, so it's our belief that more people could benefit from this option.

Thank you!

### CODE REVIEW

**Comment by Thau** [comment]
@w0rp ?

**Comment by Thau** [comment]
Still ready to merge, stalebot :P

**Review by hsanson — APPROVED** [review]
Thanks for waiting... looks good to me.

**Comment by Thau** [comment]
@hsanson, no worries, I understand you guys have quite some PRs to watch for. It's been a pleasure!

**Pull request merged**
