### PR TITLE
Have c_parse_makefile look for GNUmakefile as well

### PR DESCRIPTION
**Pull request by hugomg**
Makefiles using GNU Make features might be called "GNUmakefile" instead
of "Makefile". This commit teaches the `c_parse_makefile` feature to
look for a GNUmakefile file if a Makefile is not present.

I'm putting this in a separate PR from #3574, because it's an unrelated feature request.
Again, I'm not sure if this needs adding tests as  well. If it does then I can try to come back later to do that.

### CODE REVIEW

**Review by hsanson — CHANGES_REQUESTED** [review]
Adding tests would be good but I am not too familiar with C tests.  At least I think replicating the tests in `test_c_flag_parsing.vader` for the `ale#c#GetMakeCommand()`  method should be added. Using a different sample project than `makefile_project` that uses the GNUMakefile instead of a Makefile.

**Comment by hugomg** [comment]
Adding another test for `ale#c#GetMakeCommand` makes total sense. I'll try doing that later.

**Comment by hugomg** [comment]
A quick question... Is there a way to run the test suite without using Docker? The documentation mentions using docker for the test suite but Docker is a bit tricky to install on Fedora, which is what I'm using now.

**Review by hsanson — APPROVED** [review]
Tests seems in order. Thanks.

**Pull request merged**
