### PR TITLE
Add vim 9.0 and remove 8.0

### LINKED ISSUE #4242: Update tests to use vim 9
Now with vim 9 released we should update the CI to test ALE against it and to fix any breaking issues introduced in vim 9.

- https://github.com/vim/vim/releases/tag/v9.0.0000

### PR DESCRIPTION
**Pull request by hsanson**
Replaces vim 8.0 with vim 9.0 in the test scripts.

Closes #4242

### CODE REVIEW

**Review by w0rp — CHANGES_REQUESTED** [review]
Let's keep Vim 8.0 support and replace 8.2 in the test suite with 9.0. No reason to remove 8.0 support yet.

**Comment by hsanson** [comment]
Ok, changed the PR to keep 8.0 and remove 8.2.

**Comment by RyanSquared** [comment]
Vim 8.2 has some significant features over Vim 8.0, and is the version that I'm personally using. Is there any reason to not be testing against vim 8.2 and instead continue to support Vim 8.0?

**Comment by hsanson** [comment]
In the theorical world testing the min and max supported versions should ensure inbetween versions also work.  Except for some breaking changes between vim 8.0 and 8.2 this has been the case so far.

**Pull request merged**
