### PR TITLE
Add support for Alpine Linux APKBUILD

### PR DESCRIPTION
**Pull request by maxice8**
- Add handler for the output of atools
- Add linters for apkbuild-lint and secfixes-check from atools
- document support for apkbuild-lint and secfixes-check for apkbuild
- Make apkbuild_lint and secfixes_check default for apkbuild filetype
- Document new default linters for apkbuild
- Test default linters for apkbuild
- Add tests for atools handler, basic and dealing with Error and Warning
- Add document for apkbuild filetype

### CODE REVIEW

**Comment by maxice8** [comment]
.

**Comment by maxice8** [comment]
Rebased

**Comment by maxice8** [comment]
.

**Comment by maxice8** [comment]
..

**Comment by maxice8** [comment]
...

**Comment by maxice8** [comment]
....

**Comment by maxice8** [comment]
:shipit:

**Comment by RyanSquared** [comment]
Please don't spam comments.

**Comment by RyanSquared** [comment]
LGTM :+1:

I am not able to actively help contributing ATM but it looks fine.

**Comment by maxice8** [comment]
no

**Comment by hsanson** [comment]
ALE migrated from Travis to Github Actions (see #3548) so it is necessary to rebase this PR from latest master branch to trigger the required checks.

```
# Add dense-analysis as remote upstream on your local fork. Not 
# needed if already added.
git remote add upstream https://github.com/dense-analysis/ale.git

# Sync your local master with upstream master
git checkout master
git fetch upstream master
git merge upstream/master

# Rebase the PR branch with master
git checkout my-branch-name
git rebase master   # Fix any conflicts you may have

# Force push the updated PR branch to origin to trigger the checks
git push -f origin my-branch-name
```

**Review by hsanson — APPROVED** [review]
Looks good.

**Pull request merged**
