### PR TITLE
Add htmlbeautifier support

### PR DESCRIPTION
**Pull request by arashm**
Adds support for HTML Beautifier (https://github.com/threedaymonk/htmlbeautifier)

I tried to follow other MRs to create tests and relevant documentation.

### CODE REVIEW

**Review by hsanson — APPROVED** [review]
Looks good.

**Comment by hsanson** [comment]
Can you please also list the tool in the support-tools.md file?

**Comment by arashm** [comment]
> Can you please also list the tool in the support-tools.md file?

Done. Updated both `support-tools.md` and `ale-supported-languages-and-tools.txt`.

**Review by hsanson — APPROVED** [review]
THanks.

**Pull request merged**
