### PR TITLE
Adds support for Tlint - A Tighten Opinionated PHP Linter

### PR DESCRIPTION
**Pull request by josecanhelp**
[Tighten](https://tighten.co) has developed an opinionated PHP linter called [Tlint](https://github.com/tightenco/tlint). This pull request adds `tlint` as a PHP linting option for Ale.

All tests are passing locally and code formatting should be good to go. Thanks!

### CODE REVIEW

**Comment by josecanhelp** [comment]
Hey there! I'm hoping this comment help keeps this PR un-stale. Please let me know if there is anything I need to change here. I'm fairly certain I've dotted all the i's and crossed all the t's. Thanks!

**Comment by josecanhelp** [comment]
Can @w0rp or @hsanson take a quick peek at this one? It is pretty straightforward. Welcome any feedback. Thanks!

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by timacdonald** [comment]
Noice.

**Pull request merged**
