### PR TITLE
Set prettier working directory to where .prettierignore is

### PR DESCRIPTION
**Pull request by iclanzan**
Prettier does not use `.prettierignore` unless the current directory is the root where the `.prettierignore` file resides.

### CODE REVIEW

**Comment by RyanSquared** [comment]
related: #1095

**Comment by RyanSquared** [comment]
I don't see the reason why --stdin-filename required CdString.

**Comment by iclanzan** [comment]
@w0rp do you think we can merge this?

**Comment by w0rp** [comment]
I don't think it's the right solution. Unless the CWD is set to something, it could be anything at all. For many linters, the CWD doesn't matter. If the CWD has to be the same as the directory that `.prettierignore` is in, we should use the `ale#path#FindNearestFile` function to find it and set the CWD to that directory. That way the fixer will always use the right directory even when people have configured Vim to set the CWD to other directories.

I have Vim configured to set the CWD automatically to the directory the current file I'm editing is in.

**Comment by iclanzan** [comment]
That wouldn’t work though because many projects don’t have a `.prettierignore`.

**Comment by w0rp** [comment]
We'd handle the path possibly being there or not. Here's just one example of another tool doing a similar thing.

```vim
function! ale_linters#cpp#cquery#GetProjectRoot(buffer) abort
    " Try to find cquery configuration files first.
    let l:config = ale#path#FindNearestFile(a:buffer, '.cquery')

    if !empty(l:config)
        return fnamemodify(l:config, ':h')
    endif

    " Fall back on default project root detection.
    return ale#c#FindProjectRoot(a:buffer)
endfunction
```

**Comment by w0rp** [comment]
I've re-opened this. You can make the changes we need.

**Comment by iclanzan** [comment]
Thanks for the guidance @w0rp, I think this is ready for another review!

**Review by w0rp — APPROVED** [review]

**Comment by w0rp** [comment]
Cheers! :beers:

**Pull request merged**
